### ISSUE TITLE
Fullscreen shrinks when objects appear

### ISSUE THREAD

**Issue by LemonLake** [itdelatrisu/opsu#101]
I think this happens when sliders appear, probably due to FBOs (if they're even used, i have no clue)

Video of the issue:
https://www.youtube.com/watch?v=uo2YD8NuWDc

**Comment by Bigpet** [comment]
How do you set it to fullscreen other than setting it to the resolution of your monitor? Also, what's your GPU?

**Comment by LemonLake** [comment]
I just set it to the resolution of my monitor. Nvidia GeForce GTX 760.

**Comment by Bigpet** [comment]
Is there like a method that gets called in a hierachy when things shut down? Sort of like "init" but for shutdown? Because there's some static state that I should probably clean up if the process isn't going to be killed when the OpenGL context gets killed.

**Comment by itdelatrisu** [comment]
Most of the cleanup happens in `Container.close_sub()`,
