### ISSUE TITLE
HP remains the same when doing a slider

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#103]
For some time (probably since 0.4.0 i guess), I noticed that the HP didn't drop when doing a slider.

Everything else works fine for now

**Comment by itdelatrisu** [comment]
Sorry for the terribly late reply.  Thanks for pointing this out, I didn't even realize osu! drained HP in sliders.  Let me know if this causes any problems though (e.g. maps being impossible to pass, etc.).
