### ISSUE TITLE
[0.10.1] Sliders don't render properly

### ISSUE THREAD

**Issue by whizvox** [itdelatrisu/opsu#110]
Started happening after I updated the client today.

JRE: 8u54 x64 (Oracle)

OS: Ubuntu 15.04

![screenshot from 2015-07-23 20 23 25](https://cloud.githubusercontent.com/assets/8813286/8867024/f316642e-3178-11e5-89b1-9bb1162db535.png)

**Comment by Bigpet** [comment]
Which GPU and driver are you using?

**Comment by itdelatrisu** [comment]
Possibly fixed in #114.  Please re-open if it isn't.
