### ISSUE TITLE
Unchecked exceptions when launching 2 copies of opsu!

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#119]
When launching the 2nd opsu!, the application will immediately displays an error message:
![Error message](http://puu.sh/jzwsK.png)
Stack trace:
```
Another program is already running on port 49250.
java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:119)
```
It will be proper if the application just output a JOptionPane.showMessageBox() with a message stating there's another copy of opsu! running.

Also, is it possible to have opsu! running at a higher port than the current one? I can't get it to work at my college because there's application using that port specifically for "phoning-home" to the main server for system-related telemetry

**Comment by itdelatrisu** [comment]
What if the other program running on the port isn't opsu?

You can change the port in the config file.  49250 is an ephemeral port, so I also don't think there's any reason to change it...

**Comment by chong601** [comment]
In the case the other app, it just shows up almost exactly the same message (probably different stack message, can't confirm it because i'm on semester break for now D:)

For now, i set it to 60000 and see what's what

**Comment by itdelatrisu** [comment]
Sorry, let me clarify -- I can't just display an error message like "Another copy of opsu! is already running." because it might be a different program that's using the port, and (as far as I know) you can't use native Java to determine if that's the case.

**Comment by chong601** [comment]
oh that.
but, what if we make a detailed possible issues:
```
opsu! was unable to start because of these possible reasons:
- Another copy of opsu! is running. The application will now exit.
- Another application is using the port. In this case <procedures to changing the listening port>.
```

**Comment by itdelatrisu** [comment]
Okay, that sounds good.  Will do, thanks!
