### ISSUE TITLE
Hidden mod on opsu! doesn't fade on time

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#121]
Tested on opsu 0.10.1 commit f22498ae7dedc3b0043d601e6787fde814b11690 (on the minor update ui)

Hidden mod fades too slow on most maps (it seems to be fade properly because the notes will be removed right after you click on it if you have disabled the "Show Perfect Hits" or have been obscured by the hitobject animations if you didn't disable it or getting 100s or 50s

The note is completely hidden when it is right at the start the 300 range (iirc, need confirming).
From the fade it is using now, it is following the last possible range that a user can 300 a note.

also, the hit notes expanding out (idk what it is called, sorry about that) only happens on sliders when you click on it, reached on the other end of the slider where the ball reaches (when it have reverse arrow) and both slider start and end when it finishes, on normal circle, it only show 300,100,50 without the hit notes expanding out.

**Comment by itdelatrisu** [comment]
Could you clarify which of these is supposed to happen vs. isn't supposed to happen?

**Comment by chong601** [comment]
Intended:
on circles, the circle is totally faded including with the number when it reaches the start of 300 range and the note doesn't expand when clicked, only the score (300, 100, 50, geki, katu) shows up.
on sliders, the number fades while the entire slider body remains shows up at the same timeframe as the circle.

Actual case:
circles fade completely when the note hits the end possible range of 300, and if "Show Perfect Hits" is enabled, the note will just dissappear when clicked and if it is enabled, the note will expand when clicked and displays the score.
same case on sliders when the number fades at the same time period of 300

**Comment by itdelatrisu** [comment]
Should be fixed.  I recorded a couple of beatmaps in osu! to try to approximate the timing formulas, and they seem close, but I really have no clue if they're anywhere near accurate (I don't even know what parameters the formulas based on; I used approach time since that seemed reasonable).  Let me know if you notice any other problems.  Thanks!
