### ISSUE TITLE
Gradle-build puts a native-folder in the working directory

### ISSUE THREAD

**Issue by Lucki** [itdelatrisu/opsu#129]
I don't know whats up with the gradle-build compared to the maven-build, but it's always making a Natives folder in the working directory. I don't have something against shipping specific libs, but they should be at a specified path (with write-access when extracting at runtime), not in the working directory.

**Comment by itdelatrisu** [comment]
My bad, I forgot about this.  It's not because of Gradle, but because we removed JarSplice and aren't unpacking the natives to a temp folder anymore when running from jar (so they don't have to be re-extracted every time).  Will fix shortly.

**Comment by LemonLake** [comment]
Cheers, forgot about this.

**Comment by Lucki** [comment]
No problem! I've changed the [PKGBUILD](https://aur.archlinux.org/packages/opsu-git/) to use gradle instead of maven.
