### ISSUE TITLE
Snaking sliders

### ISSUE THREAD

**Issue by FenekAlfa** [itdelatrisu/opsu#133]
"Snaking sliders" are sliders that render gradually from start to end instead of instantly.

I didn't really notice it when Hidden wasn't available, but with HD I mess up sliders all the time because I'm too used to them from osu!. Could you add rendering snaking sliders as an option?

**Comment by itdelatrisu** [comment]
Yeah, I've been meaning to do this but still haven't gotten around to it... if you have time, it'd be really helpful if you (or anyone) could look into the mechanics of it too -- e.g. how long snaking takes relative to (probably) approach time, or if there'd be issues with the current fade-in implementation (for instance, I had to rewrite that to get "Hidden" to work at all), etc.  I usually measure these kind of things by recording several videos and going through them frame-by-frame, which is really tedious but generally works.

I don't think I'll be able to implement this for the new slider style (mmsliders) though, but someone might be able to help out after the functionality is there (for peppysliders, at least).

**Comment by Bigpet** [comment]
Yeah, I can do it for the "mmsliders" no problem. Once the timing is cleared up.

As for the mechanics. I assume that they snake in at the same rate as the "ball" moves across it (e.g they take "sliderTime" to completely snake in).

**Comment by itdelatrisu** [comment]
Awesome, thanks for offering! (And sorry I keep relying on you for this... XD)

I doubt the snaking time is related to the slider time; if you think about those swirling sliders with ~50 control points, the slider time is far too long.  I only did a quick test, but on an Easy map, I got ~506ms for snaking for a ~933ms slider.
