### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by figlet15** [itdelatrisu/opsu#137]
**Version:** 0.12.0
**Build date:** 2015-09-22 16:19
**OS:** Linux (amd64)
**JRE:** 1.8.0_60
**Error:** `** Uncaught Exception! **`
**Stack trace:**

```
java.lang.NullPointerException
    at org.newdawn.slick.opengl.ImageIOImageData.imageToByteBuffer(ImageIOImageData.java:132)
    at org.newdawn.slick.opengl.ImageIOImageData.loadImage(ImageIOImageData.java:118)
    at org.newdawn.slick.opengl.ImageIOImageData.loadImage(ImageIOImageData.java:106)
    at itdelatrisu.opsu.beatmap.ImageLoader$ImageLoaderThread.run(ImageLoader.java:96)
```

**Comment by itdelatrisu** [comment]
Do you remember what you were doing when this happened, and how often does this happen?

**Comment by figlet15** [comment]
If I remember right it happened when I exited a song right after I started it by accident. I have only seen it once

**Comment by itdelatrisu** [comment]
x.x I haven't been able to reproduce the problem and it's hard to tell what the problem is with just a trace.  Please let me know if it happens again.

**Comment by GrappigPanda** [comment]
I can't even remember how I ended up in the Java side of github, but here I am, I guess.

Regardless, could the catch exception in [imageLoader.java](opsu/beatmap/ImageLoader.java) also catch a NullPointerException? The loadImage method was working for this specific instance, but the "try-with-resources" statement was causing the exception to be thrown.

I'm not really a Java guy, but I just was cruising through github, found this and got curious.

**Comment by itdelatrisu** [comment]
I suppose so, but that doesn't give any insight to what the problem is.  Generally, I'd rather leave things like this open than catch unchecked exceptions everywhere (and not actually fix anything).

**Comment by GrappigPanda** [comment]
Ahh, I was just curious from an outsider looking in perspective. And I do guess that you should only catch an exception if you can actually do something about it. Thanks.

**Comment by itdelatrisu** [comment]
Probably safe to ignore since no one else has reported this in over a year.
