### ISSUE TITLE
Gameplay inconsistancies from native client

### ISSUE THREAD

**Issue by ploz** [itdelatrisu/opsu#138]
After a few hours of play, I've noticed a few gameplay differences between this and the native client. These may already be known but I thought I'd post.
Arch Linux x86_64; compiled (0.12.0.r0.gab81717-1)

-<del>for most (if not all) sliders, you can just hold down the input button on the slider without having to follow it and it will still yield max (300) points</del> [completely normal]
-'notes'/dots within sliders sometimes do not appear
-hp deterioration seems much slower than that of the native client. It does not seem to change much per song
-note hitbox feels slightly different
-mashing input works far too well

Overall, these differences makes the game easier than it is compared to the native client.

**Comment by itdelatrisu** [comment]
Interesting, I always thought opsu! was much harder than osu! (aside from HP). :P

* I'll look into the slider ticks when I get a chance, but do you have any more details?  (Or even one example map where this happens.)
* I have absolutely no idea what the HP formula is, and it's currently not implemented whatsoever.  Any insights are welcome.
* The hitbox is based on available sources of information, though there might be delays affecting it (from the OpenAL music player or the game loop, etc.) that are different than in osu!.  I don't think think this is an easy fix.
* Any more details about mashing input?

**Comment by Lemmmy** [comment]
any updates on this, mainly regarding hp formula?

**Comment by itdelatrisu** [comment]
HP algorithms are implemented in e62822a.  Closing this issue now.
