### ISSUE TITLE
hey , i have a problem on download song on opsu l the problem is like java or JSON , im using samsung galaxy tab A , can you fix it?

### ISSUE THREAD

**Issue by kirito587** [itdelatrisu/opsu#139]

**Comment by kirito587** [comment]
It said cannot create JSON something and about java

**Comment by Bigpet** [comment]
can you write down the exact error message and tell us what you were doing when it appeared (or upload a screenshot if you don't want to type the message).

**Comment by omar2623** [comment]
Same thing with me, it's happening to me as well. I then deleted opsu and installed it again and it still showed the same thing

**Comment by omar2623** [comment]
If you can please fix or update opsu because i really love playing it. This error wont let me download songs  >_<

**Comment by fluddokt** [comment]
**Version:** 0.12.0
**OS:** Windows 8.1 (x86)
**JRE:** 1.7.0_67
**Error:** `Failed to create JSON object.`
**Stack trace:**
```
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at itdelatrisu.opsu.Utils.readJsonObjectFromUrl(Utils.java:411)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:71)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:213)
	at java.lang.Thread.run(Unknown Source)
```

Seems like bloodcat changed something.
Other servers seem to be working fine.

**Comment by itdelatrisu** [comment]
Thanks for the report -- fixed.  I'll probably make a hotfix release in the next few days or so when I get a chance (I'm kind of busy right now, sorry!).  In the meantime, just use a different server and ignore the warning.

**Comment by Lemmmy** [comment]
Note to @kirito587: This update might not be on Android until the next version. As @itdelatrisu mentioned, you will have to use a different beatmap server for now.

**Comment by omar2623** [comment]
But im trying to go to a different server and when i download a song there, it doesnt show up on my playlist

**Comment by Lemmmy** [comment]
Have you clicked "Import All" in the downloads list?

**Comment by omar2623** [comment]
Yes i have, it still doesnt want to show

**Comment by omar2623** [comment]
Wait nevermind, its working


And if its not too much to ask, can you make it so the wallpaper for beatmaps or songs fill up the whole screen while playing, that'll be so amazing

**Comment by itdelatrisu** [comment]
Uploaded 0.12.1 release that fixes this issue.

@omar2623: What do you mean?  Isn't that what already happens?

**Comment by omar2623** [comment]
When i go into the playlist it fills up the whole screen but when i start to play one, some of them arent fully covering the whole screen.

For example - BRAVELY YOU fills up the whole screen while im playing any mode. But SHINY SHINY doesnt fill up the whole screen, the sides show black

**Comment by itdelatrisu** [comment]
That's what osu! does too.  In the game, the aspect ratio of the image is preserved; in the menus, the image is stretched to fit the screen.  If you want to change this, you just have to change the last `false` to `true` in this part of `src/itdelatrisu/opsu/states/Game.java`:
```
beatmap.drawBackground(width, height, dimLevel, false)
```

**Comment by fluddokt** [comment]
Osu seems to actually only fit to screen some of the images in game (which somewhat annoyed me). Perhaps I can add an option to determine how It will be stretched. Such as "fit to screen"(currently) , "fill screen"(songMenu) , "fit to screen height", "stretch to screen"(before).

**Comment by angjinhang** [comment]
Until now from what I know, osu! preserves all image ratios no matter in game or in menu. If the image is 4:3 and your screen is 16:9 osu! will just enlarge the image till it fills up your whole screen. However for black sides it happens when you have a storyboard and it don't have widescreen support (that's the beatmap side problem), maybe videos too but I'm not sure about it.

**Comment by omar2623** [comment]
By the way, how do i change the skin, i seen other people with nice different skins, how do i change it on an android?

**Comment by Lemmmy** [comment]
To change the skin, place the texture files in `/(main storage)/opsu/Skins`.

**Comment by omar2623** [comment]
Do you have a kik? So i can get more info on how to do it and where to get it and send you screenshots of the folders shown

**Comment by Lemmmy** [comment]
I do not, and I cannot provide an example at the moment. I will try and get a video for you at some point.

**Comment by omar2623** [comment]
Thank you
