### ISSUE TITLE
osu! trademark

### ISSUE THREAD

**Issue by FenekAlfa** [itdelatrisu/opsu#142]
blog.ppy.sh/post/129218889833/20150916

So apparently peppy wants to trademark osu!(good thing someone on reddit caught that). Might be a good idea to remove all of the "osu!"s in the game and repo to avoid lawsuits, which knowing peppy will come quite quickly. Besides, this is also a good opportunity to fix the description, because "osu! client" implies that you connect to osu!'s network, which peppy said numerous times won't happen even for modifications of the official client, let alone a completely different one. My suggestion is "A free game about clicking circles mapped to the beat".

**Comment by Bigpet** [comment]
I don't think it's such a dramatic thing. Doesn't this just mean that there needs to be a "osu! is a registered trademark of xyz" disclaimer? I don't think opsu uses the "osu!" term in a way that would break  trademark law.

I'd say wait and see. Also, I doubt anyone would straight up jump to a lawsuit (also, who are they gonna sue). I assume there would be a cease and desist letter first.

**Comment by chong601** [comment]
if opsu! does cause issues with osu! name, wouldn't peppy already shout this out right as soon as the thread (or this project started)?

**Comment by itdelatrisu** [comment]
I'll remove any mentions of "osu!" if I'm asked to do so, but I also doubt it's going to be an issue.  I can add the trademark disclaimer when needed.
