### ISSUE TITLE
[Feature Request] Add more stuff from this post

### ISSUE THREAD

**Issue by Pepperrika** [itdelatrisu/opsu#144]
Hello! I thought i would give you a bit of features you could use in opsu!
Features you could use:
A better opsu! logo 
New combo burst's (plz only use one combo burst this time)
Online servers!
Online multiplayer!
Irc chat!
It might be alot but i hope it goes well

**Comment by angjinhang** [comment]
Online servers, multiplayer, irc... This doesn't need only code but also
money to run a server. Not easy for an open source project though as the
cost involved will be really high.

opsu might need sponsors from the player base for this to happen lol.

**Comment by itdelatrisu** [comment]
You can skin any images -- it works the same way as in osu! except you can even skin the logo, etc.  If you have suggestions for a new logo design, go ahead and post them!

I don't have the time to write a server, and I doubt anyone else will either.  It's a huge task.

I almost never use IRC anymore, but feel free to start your own channel if you find that other people are interested in one as well.

(You can keep replying here, but I'm going to close the issue.)

**Comment by Lemmmy** [comment]
Isn't chong601 working on multiplayer?

**Comment by chong601** [comment]
>Isn't chong601 working on multiplayer?

I actually did a simple multiplayer system at first (using JSP).
But after considering the base for a multiplayer system, i decided
that with my workload and things happening right now, i scrapped the
project.

Also,
>A better opsu! logo 

As @itdelatrisu says, you can edit them (its in `res/` folder anyway)
>New combo burst's (plz only use one combo burst this time)

Also, you can change them in `res/` folder as well

>Online servers!

money please
>Irc chat!

implementing IRC on opsu!? k
the chat console? probably need to think twice

**Comment by Lemmmy** [comment]
Actually, at some point I might set up an opsu! IRC server and make a basic in-game chat and bot for it.
