### ISSUE TITLE
[Feature Request] Android Opsu! on Extsdcard

### ISSUE THREAD

**Issue by skyhot004** [itdelatrisu/opsu#147]
Make app able to be put on sd card
Specifically at the beatmaps files
These files are big

And in case you are on android 4.4
Make pre directory in Extsdcard/Android/Data/

Interest of Opsu! folder in root of memory card cause android 4.4 won't be able to put files on sd card if you put it that way

PS.Not sure if I requested at the right place 
First time using github

**Comment by itdelatrisu** [comment]
Thanks for the idea!  You'll want to post [here](https://github.com/fluddokt/opsu/issues) instead, though, since this repository is for the desktop.
