### ISSUE TITLE
[Feature Request] Music video support?

### ISSUE THREAD

**Issue by cyalins** [itdelatrisu/opsu#151]
Would it be possible to add support for videos sometime in the future?
I can't seem to find any info regarding this, and I'm not sure if this has been asked before.

Thanks!

**Comment by itdelatrisu** [comment]
Maybe, but it seems unlikely.  From what I can find, there aren't that many options for video playback in LWJGL, and the available libraries come with huge natives (for each OS).

Here's one solution using gStreamer, though: http://www.java-gaming.org/topics/gstreamer-in-lwjgl/24852/msg/242092/view.html#msg242092
And a backup of the classes that Cero wrote, just in case:
* [SlickApp.java](http://pastebin.com/raw.php?i=8kevr7vG)
* [GStreamerPlayer.java](http://pastebin.com/raw.php?i=Jw1BuUup)

**Comment by Retalyx** [comment]
It would be really great and appreciated :D

**Comment by itdelatrisu** [comment]
Done in e6c90ad.
