### ISSUE TITLE
Freezy Spinners on Android

### ISSUE THREAD

**Issue by Retalyx** [itdelatrisu/opsu#154]
Hi , i'M playing with Opsu on a Samsung Galaxy Alpha , running Android 5.0.2 the problem is that while i'm playing , the games , the sound, everything is good and without lag or freeze , but... if there is a spinner on the screen, i'll have many freeze until the spinner disappear :/ cause of that I can't reach half of the spinners because the half of time it's frozen

Thanks

**Comment by itdelatrisu** [comment]
Please report this [here](https://github.com/fluddokt/opsu/issues) instead -- that's the page for Android reports.  Thanks!
