### ISSUE TITLE
[Feature Request] Reverse Arrow,And Slider followcircle

### ISSUE THREAD

**Issue by honard** [itdelatrisu/opsu#167]
Can u add Bumping effects in the reverse arrows in a slider?

and about the Slider Followcircle 
can u add the featurewhen starting to follow the slider,the slider follow circle appears with soft kinetic movement,and when the slider is finished ,the slider follow circle will shrink until it fits to the Slider end circle

thanks for the feedback

**Comment by Lemmmy** [comment]
@itdelatrisu is this issue finished with #210?

**Comment by itdelatrisu** [comment]
Only the bouncing reverse arrow was addressed in #210 but I took it out since it looks dumb with the current reversearrow image (or any that fit the entire hit circle).

Took care of all follow circle animations in 99c698b.
