### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by TheLastProject** [itdelatrisu/opsu#172]
I just found out about opsu today, it's definitely pretty cool! Is there any chance you would be willing to release this to [F-Droid](https://f-droid.org/)?

You could either set it up as explained in [fdroiddata's Contributing.md file](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md) or simply submit it to the [submission queue](https://f-droid.org/forums/forum/submission-queue/).

If you do not want to bother with this yourself, I will happily submit it to the submission queue for you, but I figured I'd at very least give you a heads up first.

**Comment by mad-s** [comment]
This repository is for the desktop version. Check https://github.com/fluddokt/opsu for the android version.

**Comment by TheLastProject** [comment]
Made a new issue downstream, will close this one.
