### ISSUE TITLE
Where is config file?

### ISSUE THREAD

**Issue by JDarkMatteR** [itdelatrisu/opsu#179]
I downloaded from the .jar file, but when I startup the game, it tells me another program is bound to port 49250, and that I can change the port in the config file. If I change the port in the config, the error message stays there, and I am not running another instance of the game.
![screenshot from 2016-02-11 16 54 53](https://cloud.githubusercontent.com/assets/11953085/12994812/6a5ef88c-d0e0-11e5-9dd0-e9871d932a03.png)

**Comment by mad-s** [comment]
The config should be in `~/.config/opsu/.opsu.cfg`. Be aware that files and folders starting with a dot are invisible, so set your file explorer to show hidden files. There should be a line saying `Port = 49250` in the config file. If there isn't, you can probably just add a line saying `Port = 49250`.

**Comment by JDarkMatteR** [comment]
Ctrl+H is already enabled.

**Comment by Lemmmy** [comment]
@JDarkMatteR Did the suggested fix solve your issue?

**Comment by Swimgiant** [comment]
I am getting the same issue and when I change the port nothing happens, except the port listed on the error window
