### ISSUE TITLE
Random freezes on Linux 4.4

### ISSUE THREAD

**Issue by tpenguinltg** [itdelatrisu/opsu#182]
I experience frustrating random second-long freezes while playing on Arch Linux with kernel version 4.4 (currently the latest in the repos). I see no CPU or disk usage spikes at the time of the freeze, nor is anything logged to the log file. It seems to happen regardless of the number of songs I have and the underlying filesystem. This occurs on both opsu v0.12.1 (7245673) and the latest master HEAD (93c8ab9).

I don't experience these freezes with kernel version 4.3 with the exact same settings.

I have an Intel graphics card, and I'm running on OpenJDK 8, if that matters.

**Comment by itdelatrisu** [comment]
Sorry for the super late reply.  This doesn't seem worth investigating, as it's almost certainly caused by some external issue and only you (or anyone else with this problem) would be able to debug it anyway.

**Comment by tpenguinltg** [comment]
For posterity, it seems the issue is with OpenGL and the kernel's process scheduler. I still don't have a solution, but it indeed has nothing to do with opsu!.

**Comment by tpenguinltg** [comment]
For what it's worth, the problem seems to have gone away in 4.16.
