### ISSUE TITLE
Fix stacking algorithm 

### ISSUE THREAD

**Issue by AndreySeVeN** [itdelatrisu/opsu#183]
float mapDifficultyRange(float difficulty, float min, float mid, float max)
{
    if (difficulty > 5.0f)
        return mid + (max - mid)_(difficulty - 5.0f) / 5.0f;
    if (difficulty < 5.0f)
        return mid - (mid - min)_(5.0f - difficulty) / 5.0f;
    return mid;
}
STACK_TIMEOUT = mapDifficultyRange(overallDifficulty, 1800.0f, 1200.0f, 450.0f);

https://github.com/itdelatrisu/opsu/blob/1e58b3c47d4cdd9d07c619209413cd9fdb2f84d8/src/itdelatrisu/opsu/states/Game.java#L1858

**Comment by iceblade112** [comment]
Psst, try a pull request!

**Comment by itdelatrisu** [comment]
Fixed in 9b5f26d, thanks!
