### ISSUE TITLE
[Feature Request] make the UI have a similar layout like in osu! LAZER

### ISSUE THREAD

**Issue by sr229** [itdelatrisu/opsu#188]
since the new UI introduced by LAZER looks promising, maybe we should also implement a similar-looking UI?

**Comment by Lemmmy** [comment]
ok

**Comment by iceblade112** [comment]
yeah, sure.

soo... who's this "we" you speak of?

**Comment by virgil9306** [comment]
Need more description than "looks promising" - why do you think it's promising from a technical, UX, etc. standpoint? Not saying it's a bad idea, but it's not worth the work based on such a vague description, since no one has that kind of time lol.

**Comment by iceblade112** [comment]
Pretty much what @virgil9306 said. It's not finalized, either, so there could be changes before osu!next (which I expect by 2070)...

**Comment by Lemmmy** [comment]
im not defending poopy or anything but at least development of it is closer than it was last year

**Comment by iceblade112** [comment]
Shhhh...
