### ISSUE TITLE
Feature Request - Video Background 

### ISSUE THREAD

**Issue by TheVicBro** [itdelatrisu/opsu#190]
Can you please add it so a video plays in the background if available. Make it an option (On/Off) as some devices will not be able to handle it, but I know that my can (Nexus 6P), thanks!

**Comment by iceblade112** [comment]
Is there even a reason to add those? Typically, higher ranked people don't use video since it's distracting and annoying.

**Comment by TheVicBro** [comment]
I'm more of a casual player and I really like it, and I'm sure others could agree. Besides it's just a nice option, higher ranked players can turn it off if they want.

**Comment by iceblade112** [comment]
Well, seeing as the project is open source... if you really like that feature, it's probably time for you to read up on Java. :smile:

**Comment by TheVicBro** [comment]
Haha maybe, I always been interested in coding and computers. But I might not have the time for it, but there's still a chance! 😁

**Comment by itdelatrisu** [comment]
Probably not happening, video playback in LWJGL would need to be coded from scratch.
