### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by RyoukoX3** [itdelatrisu/opsu#197]
**Version:** 0.12.1
**Build date:** 2016-10-01 21:41
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_101
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:652)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:590)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:307)
	at itdelatrisu.opsu.Container.close_sub(Container.java:113)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:204)
```

**Comment by iceblade112** [comment]
This is a dupe, or 5. Search for "setDefaultImage".

If you're on Windows 10, are you using Microsoft-supplied drivers or vendor-supplied drivers?

**Comment by RyoukoX3** [comment]
Vendor Supplied

**Comment by RyoukoX3** [comment]
http://pastebin.com/raw/pueX8wT2


if that helps

**Comment by iceblade112** [comment]
Yup, what graphics card do you have?

This line says it all: Pixel format not accelerated

**Comment by RyoukoX3** [comment]
Intel Hd Graphics 3000

**Comment by iceblade112** [comment]
I found this: https://github.com/LWJGL/lwjgl/issues/119#issuecomment-246253705

**Comment by RyoukoX3** [comment]
Worked. Thank you very much

**Comment by RyoukoX3** [comment]
After a few days no it says the same Error

**Comment by iceblade112** [comment]
Pretty much, this is an issue with the Intel drivers that Intel will not fix. Your graphics card is considered a potato, and it'll never be fixed. Your only choice is to use old JRE/JDK if you want to use an LWJGL application.

**Comment by RyoukoX3** [comment]
i hate potatos :< ty anyways
