### ISSUE TITLE
Snaking sliders are cut off

### ISSUE THREAD

**Issue by itdelatrisu** [itdelatrisu/opsu#215]
Snaking sliders should be rounded, but are cut off (in #205).  This is noticeable with the higher-level slider changes in #211, when the end hit circle is faded in after snaking completes (as in osu!).

@mad-s, how difficult would it be to change this?

**Comment by mad-s** [comment]
It would not be too hard to implement.
My solution would be to draw a (semi-)cone at the end of the curve. However, performance might suffer a bit, since an additional shader change (and uniform changes) per frame would be necessary.
