### ISSUE TITLE
ErrorHandler doesn't show correct stacktrace

### ISSUE THREAD

**Issue by yugecin** [itdelatrisu/opsu#218]
The problem with these crash reports (#135, #185, #193, #195, #200, #204, #206) is that the real cause doesn't get caught.

Take a look at https://github.com/itdelatrisu/opsu/blob/af667a48d5178948207a9dc01d2d1c3974106c43/src/itdelatrisu/opsu/Container.java#L75
It has no catch block, so the real cause is lost. Therefor the stacktrace in those issues are just showing a different exception which is a side effect of the game shutting down after a crash.

To get usable traces, it should be caught in a similar fashion to this
https://github.com/yugecin/opsu-dance/blob/e878f0fb0de6d8b4090987f7e6704cb0f15c5efe/src/itdelatrisu/opsu/Container.java#L70

**Comment by itdelatrisu** [comment]
Have you noticed that this actually helps?

Correct me if I'm wrong, but I don't think this should produce any better traces.  Any uncaught exceptions just hit the `UncaughtExceptionHandler` immediately, which should then show the most accurate trace.  (The main reason the `Container` class exists is to log the exceptions that Slick swallows.)

**Comment by itdelatrisu** [comment]
Fixed in 8b7b7e0, let me know if you have any comments.

**Comment by yugecin** [comment]
Oh yes that makes more sense, nice.
I tried finding out whether what I said made a difference and I couldn't find one. I was convinced it worked because I didn't see those obscure exceptions anymore after I added that, it was probably just coincidence.
