### ISSUE TITLE
Disable mouse option anomalies

### ISSUE THREAD

**Issue by yugecin** [itdelatrisu/opsu#220]
There are 2 options regarding mouse settings:
* disable mouse wheel in play mode
* disable mouse buttons in play mode

I enabled the option to disable the buttons, but left the wheel option disabled. I expected to be still able to change the volume by scrolling, but the button option also disables the scrolling functionality, which is not very logical in my opinion.

So my suggestion would be to change https://github.com/itdelatrisu/opsu/blob/master/src/itdelatrisu/opsu/states/Game.java#L1216 to only check if the mouse wheel is disabled.

Perhaps even another option can be added, to disable the mouse wheel button. That way players can use any combination they'd prefer, eg disabling left and rightclick and middleclick but still change volume by scrolling.

**Comment by itdelatrisu** [comment]
That's a bug, not sure why I wrote that. 😕 Thanks for catching this.  (Not going to add another option since I'm mostly mimicking osu! with this, and I don't think that extra option is particularly useful.)
