### ISSUE TITLE
Main logo pulsing is inconsistent with footer logo pulsing

### ISSUE THREAD

**Issue by tpenguinltg** [itdelatrisu/opsu#223]
The main logo shrinks on beat and leaves a ghost, while the footer logo grows on beat and radiates a ghost. These two should have the same animation. I vote to keep the footer logo's animation to keep par with osu proper and because it looks better.

**Comment by itdelatrisu** [comment]
osu! has the same behavior (as of right now) -- shrinking on beats in the main menu and expanding in the song menu.  I also think it looks fine.

**Comment by tpenguinltg** [comment]
I guess my second-hand information is wrong, then; I don't have a copy of osu! to double-check with. I'll close this now since it seems like a non-issue, but feel free to re-open it if you think it should stick around.
