### ISSUE TITLE
Failed to load file 'C:\Users\Anyone\AppData\Local\osu!\Skins\Phaze1.6\drum-slidertick.wav'.

### ISSUE THREAD

**Issue by iNitroPlays** [itdelatrisu/opsu#230]
**Version:** 0.13.0
**Build date:** 2016-12-27 05:03
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_92
**OpenGL Version:** 4.4.0 - Build 20.19.15.4352 (Intel)
**Error:** `Failed to load file 'C:\Users\Anyone\AppData\Local\osu!\Skins\Phaze1.6\drum-slidertick.wav'.`
**Stack trace:**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:95)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:235)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:157)
```

**Comment by Lemmmy** [comment]
your opsu installation is in a folder with `!` in the name, or is junctioned to one. move opsu to a folder without `!` in the name, and it will work.

**Comment by itdelatrisu** [comment]
@Lemmmy: That's not the issue, he's loading the file from an external skin.

Here are the files that don't work - they're encoded in GSM 6.10.
[samples.zip](https://github.com/itdelatrisu/opsu/files/690673/samples.zip)

**Comment by Lemmmy** [comment]
why/how is the skin external

**Comment by itdelatrisu** [comment]
It's a skin in his osu! installation directory, not within the opsu! jar.

I tried including the Tritonus GSM 06.10 codec (in the `tritonus-all` maven artifact), but just got this error instead:
```
java.lang.IllegalArgumentException: Unsupported conversion: PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian from GSM0610 44100.0 Hz, unknown bits per sample, mono, 65 bytes/frame, 137.8125 frames/second, 
```

**Comment by itdelatrisu** [comment]
Did more research, and this isn't possible in Java.  See 8655794.
