### ISSUE TITLE
No sound at all

### ISSUE THREAD

**Issue by Bunui** [itdelatrisu/opsu#234]
Version: 0.14.0
OS: Windows

Upon opening there is no sound at all anywhere. I tried to delete everything and download the .jar again, but this failed to fix the problem.

**Comment by Lemmmy** [comment]
@Bunui do you see opsu! anywhere in the Windows Sound Mixer? Click the volume icon and hit Mixer, and see if opsu! is listed anywhere. It may also be in another device - click your audio device (e.g. speaker, headphones) and look for opsu! under there.

**Comment by itdelatrisu** [comment]
Closing, feel free to keep commenting if those suggestions to fix the issue.
