### ISSUE TITLE
0.14.0 APK

### ISSUE THREAD

**Issue by flazep3** [itdelatrisu/opsu#236]
We really need android version of the newest version because its useless on pc since we have original osu! I have no way of contacting fluddokt so, if you can contact him, please ask him to port it to android or if you can do it yourself, please do it! Keep that in mind, i am not forcing you guys!

**Comment by itdelatrisu** [comment]
I don't have any method of contacting either, or any real interest in maintaining that port due to time commitment.  Sorry.

**Comment by tpenguinltg** [comment]
It's a long shot, but doing a user mention might help:
@fluddokt

**Comment by ilhamdkk** [comment]
Screan blank to load beatmap android 5.0

**Comment by Lemmmy** [comment]
@ilhamdkk this isn't the right place to post this. Did you click "Import All" in the downloads menu after downloading maps?
