### ISSUE TITLE
i cant open opsu :c

### ISSUE THREAD

**Issue by Tmuru321** [itdelatrisu/opsu#239]
![image](https://cloud.githubusercontent.com/assets/18645265/22319708/057ed076-e364-11e6-9d43-cfc5033788b0.png) 
this happend when i open it

**Comment by tpenguinltg** [comment]
It looks like you're trying to open opsu!dance and not plain opsu!. If so, perhaps you should [open an issue there](https://github.com/yugecin/opsu-dance) instead.

**Comment by itdelatrisu** [comment]
Yeah, not an issue from this project.  Good luck.
