### ISSUE TITLE
"Unknown" keys treated as KEY_EQUALS

### ISSUE THREAD

**Issue by tpenguinltg** [itdelatrisu/opsu#242]
Certain keys seem to be erroneously recognized as `Input.KEY_EQUALS`. This is evident when pressing these keys in the pause screen: the "Offset can only be changed while game is not paused." notification appears, as well as during gameplay where pressing one of these keys will increase the beatmap's offset. I suspect this behaviour has existed even before local beat offsets were introduced, although it wasn't evident because `KEY_EQUALS` wasn't being used.

Here are the keys that I've noticed are erroneously detected as `KEY_EQUALS`:

* Windows key (both left and right)
* [Menu key](https://en.wikipedia.org/wiki/Menu_key)
* Print Screen
* `\` / `|` key
* Media/Application keys (play/pause, back, forward, lock, calculator, brightness up, brightness down, etc.)

OS: Arch Linux x64
opsu commit a835c54 (behaviour has been around since at least e023780)

**Comment by itdelatrisu** [comment]
Yeah, noticed this too and forgot about it -- thanks for reporting.

Apparently this was caused by a "fix" in Slick2D, but I couldn't reproduce the supposed bug so I reverted the change.  Anyhow, let me know if the `=` key suddenly stops working for you...

**Comment by tpenguinltg** [comment]
That seems to have fixed it and the `=` key still works. Thanks!

For the record, it seems the forum post referenced in the comment was moved to a new domain: http://slick.ninjacave.com/forum/viewtopic.php?t=617
I haven't found a follow-up to the topic and the workaround is still present in the latest version, but if it's unreproducible, then I guess LWJGL fixed the issue and they forgot about it.

**Comment by itdelatrisu** [comment]
Oh, thanks for the link.  I think we can assume it was fixed if we couldn't reproduce in Windows or Linux and the thread is nearly 10 years old.
