### ISSUE TITLE
Option hover indicator misaligned on later options

### ISSUE THREAD

**Issue by tpenguinltg** [itdelatrisu/opsu#243]
With the resolution set to something with a height less than 768 (e.g. 1280x720 or 800x600), open the options overlay, scroll down to the end and hover over an option. The hover indicator is offset. I suspect this also happens with resolutions with a height of 768 or greater, but the effect isn't as noticeable.
![screenshot_20170131_191414](https://cloud.githubusercontent.com/assets/8697332/22490262/3de6aed6-e7ea-11e6-9a81-4997985563cd.png)

Arch Linux x64
opsu! commit 0fd7c35

**Comment by itdelatrisu** [comment]
My bad, fixed in 51b25e3.  Thanks for catching these things all the time. :)

Off-topic: Are music videos working on your OS?  And let me know if you find any issues with that or the user system too! xD

**Comment by tpenguinltg** [comment]
Glad to be of service. I just wish I had the time and knowledge of the codebase to put in more pull requests.

I keep videos off because they're too distracting, but I tried it out when you first implemented it. The playback works for all the videos that I've tested, but some are distorted, like below. I haven't yet figured out what's different about the distorted videos.
![screenshot_20170131_201811](https://cloud.githubusercontent.com/assets/8697332/22491605/af0c85ce-e7f2-11e6-8a68-8d079229419a.png)
However, the distortion is probably because I linked it to my system FFmpeg (v3.2.2), so I can't really complain.

I'll be sure to watch out for issues in the user system (great feature, by the way). I have a couple of enhancement ideas, but I have to determine if there are use cases before I suggest them.

**Comment by fluddokt** [comment]
https://www.opengl.org/discussion_boards/showthread.php/171071-glTexSubImage2D-and-buffer-width
adding 

GL11.glPixelStorei ( GL11.GL_UNPACK_ALIGNMENT, 1 ) ;
GL11.glPixelStorei ( GL11.GL_PACK_ALIGNMENT , 1 ) ;

somewhere should fix the distortion.

**Comment by itdelatrisu** [comment]
Interesting, do I wrap it around this line? https://github.com/itdelatrisu/opsu/blob/master/src/itdelatrisu/opsu/video/Video.java#L209

Can't test it myself since I haven't been able to reproduce. x_x

**Comment by fluddokt** [comment]
It only needs to run once so putting it in the constructor should be fine.

As an example https://osu.ppy.sh/s/122605 video distorts for me.

**Comment by itdelatrisu** [comment]
Done in 58c4d60, thank you!

**Comment by tpenguinltg** [comment]
Works for my system FFmpeg, too. Thanks!
