### ISSUE TITLE
Failed to initialise the LWJGL display

### ISSUE THREAD

**Issue by christianarce** [itdelatrisu/opsu#250]
**Version:** 0.14.0
**Build date:** 2017-01-09 07:37
**OS:** Windows XP (x86)
**JRE:** 1.8.0_121
**Stack trace:**
```
org.newdawn.slick.SlickException: Failed to initialise the LWJGL display
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:378)
	at itdelatrisu.opsu.Container.start(Container.java:72)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```

**Comment by itdelatrisu** [comment]
Can you try running the jar with `-Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true`?  i.e.
```
java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true -jar opsu-0.14.0.jar
```

(Linking #248.)

**Comment by christianarce** [comment]
I got it, I didn't have the video drivers installed. Thanks anyway <3
