### ISSUE TITLE
Certain Wav Files Fail to Play Ubuntu 16.04

### ISSUE THREAD

**Issue by chanceVermilion** [itdelatrisu/opsu#251]
I've been working in a branch to improve sound effects and hit sound issues on linux. I've made good progress, but there are a handful of clips that are problematic. When opsu tries to play them, especially the sliders, it slows down considerably. I imagine this is some problem with the Java pulse audio implementation. However, I can't use Totem or Rhythmbox to play these clips either so I'm thinking there's some kind of codec issue. I have ubuntu-restricted-extras installed. Here's the list.

- drum-sliderslide.wav
- drum-slidertick.wav
- drum-sliderwhistle.wav
- normal-sliderslide.wav
- normal-slidertick.wav
- normal-sliderwhistle.wav
- soft-sliderslide.wav
- spinnerspin.wav

Something I've noticed is that most of the clips that fail to play are single channel 16-bit depth files. I'm going to continue looking into this, but I don't have a lot of experience with wav format issues.

**Comment by itdelatrisu** [comment]
Thanks for looking into the issue.  I have no experience with audio in Linux, so sorry I won't really be able to help.

**Comment by chanceVermilion** [comment]
The equivalent files in [osu-resources](https://github.com/ppy/osu-resources/tree/master/osu.Game.Resources/Samples/Gameplay) all play on my machine.

**Comment by itdelatrisu** [comment]
Just noticed that all those files are actually just empty tracks... =_=

Does this work? [sounds.zip](https://github.com/itdelatrisu/opsu/files/752791/sounds.zip)
It's a 10ms stereo 16-bit 44.1KHz PCM clip duplicated with all those file names.

**Comment by itdelatrisu** [comment]
For good measure, re-encoded everything that wasn't in that format:
[new_sounds.zip](https://github.com/itdelatrisu/opsu/files/752799/new_sounds.zip)

Let me know if all of those work too, if you don't mind?

**Comment by chanceVermilion** [comment]
Unfortunately those same 8 files still fail to play.

**Comment by itdelatrisu** [comment]
What do you mean by "fail to play"?

**Comment by chanceVermilion** [comment]
"Fail to play" is inaccurate now that I think about it. When I open those files with something like ffplay or the other applications I mentioned initially, I hear no audio.

**Comment by itdelatrisu** [comment]
There is no audio - those sound files are empty.  What I'm concerned about is your statement:
> When opsu tries to play them, especially the sliders, it slows down considerably.
Does that still happen with the new files?

**Comment by chanceVermilion** [comment]
Ah, I understand now. It turns out that the slowdown is a separate problem caused by PulseAudioClips not stopping correctly. I've addressed it in #252. It was noticeable on sliders because of how quickly a bunch of clips have to be played. When running with the changes in that PR, I saw no slowdown with either the empty files or the ones I grabbed from osu-resources.
