### ISSUE TITLE
Slider followcircle shrinks on repeats

### ISSUE THREAD

**Issue by yugecin** [itdelatrisu/opsu#260]
The slider followcircle shrinks on repeats, which looks a bit weird imo. I don't know if this is intended?
![w](https://cloud.githubusercontent.com/assets/12662260/23338885/5412dd8e-fc16-11e6-9350-5355835aad61.gif)

It should behave like slider ticks, a small bump:
![g](https://cloud.githubusercontent.com/assets/12662260/23338888/6419d1b0-fc16-11e6-90c5-54b04fc79381.gif)

**Comment by itdelatrisu** [comment]
Thanks for pointing that out! Fixed in 12dccb6.

BTW, how much work would it be to implement your slider rendering as an option in this repo?  (It looks really cool!)  I looked at your code for a bit, and it looks like you had to make a lot of changes?

**Comment by yugecin** [comment]
Thanks! Indeed there are lots of differences in the meantime. I guess it depends on how much the new sliderstyle changed (#205), I haven't looked into that yet. This style still uses the old(er) method. Overall I think it should be reasonable, if I just copy the code that I have. I'll try to add them when I find the time.
