### ISSUE TITLE
Experimental slider tracks not falling on failure

### ISSUE THREAD

**Issue by tpenguinltg** [itdelatrisu/opsu#266]
With experimental sliders and merging sliders enabled, the slider tracks don't fall on failure. They also continue to shrink if shrinking sliders are enabled (may or may not be correct, because balls still continue to roll with regular sliders).

With shrinking sliders:
![screenshot_2017-03-10_20-46-30](https://cloud.githubusercontent.com/assets/8697332/23819382/70766236-05d3-11e7-94e5-8b22008b6a89.png)

Without shrinking sliders:
![screenshot_2017-03-10_20-49-40](https://cloud.githubusercontent.com/assets/8697332/23819385/98a0506e-05d3-11e7-9ccc-0034f4081d90.png)

They fall as expected when merging sliders is disabled.

opsu! commit 8dd92de

**Comment by itdelatrisu** [comment]
Thanks for reporting. Tagging @yugecin. (I might not have a chance to look at this for a while. x_x)

**Comment by tpenguinltg** [comment]
I think I see the problem. It looks like the merged sliders are being drawn directly instead of being added to the hit object stack ([Game.java:1633](https://github.com/itdelatrisu/opsu/blob/06370bd055ac37f23562500bbf173191558f543a/src/itdelatrisu/opsu/states/Game.java#L1633)), so the transformations to make it fall aren't being done on it. I'm not quite sure how to fix this, though, because a `Graphics` object isn't being passed to the merged slider's `draw` method. I assume that the merged slider should fall as a unit rather than breaking up into its component parts.

**Comment by yugecin** [comment]
The solution is to force non-merged sliders when they are falling, making fix atm.
