### ISSUE TITLE
Drag&drop

### ISSUE THREAD

**Issue by TaylerNest** [itdelatrisu/opsu#270]
One of most commonly used functionality - drag and drop opening of beatmaps and skins. I know that's a huge task, but it _should_ be implemented one day.
At least it doesn't works in XFCE

**Comment by Lemmmy** [comment]
actually usually people just click the file and it opens but drag and drop is nice

**Comment by itdelatrisu** [comment]
Not going to happen given the current framework, sorry.  File drag and drop is a new feature in LWJGL3, but we're stuck on LWJGL2 because that's what Slick2D uses and Slick2D is long dead.

**Comment by TaylerNest** [comment]
Why not moving to LibGDX

**Comment by itdelatrisu** [comment]
Mostly because there's almost 40k lines of code already, and it's easier/faster for me to develop in the current environment than libGDX when I tried it.

**Comment by TaylerNest** [comment]
Sadly, but you probably have to start moving in a separate branch. Maybe even rewriting. opsu is unplayable, honestly...

**Comment by itdelatrisu** [comment]
Then don't play it. :/

**Comment by yugecin** [comment]
This got negative pretty quickly... Surely this one missing feature doesn't make it unplayable. You can always help by contributing code or making issues for bugs or features that you're missing (like this one), but of course not everything can be resolved. Making an exact bugfree clone would require an enormous effort, which is not always doable.

**Comment by Lemmmy** [comment]
its only 27k lines

**Comment by TaylerNest** [comment]
I didn't meant that this feature makes game unplayable, just try to play opsu right after official osu. It feels awfully. I mean that without new things like libgdx there is not much way you can make this actually playable. Like there is no point of maintaining it as nobody really can play it. Sorry if it looks destructive...

**Comment by itdelatrisu** [comment]
Oh, I see.  I'll go ahead and shut down the project, then... /s
