### ISSUE TITLE
Fail sound doesnt stop after exiting fail menu.

### ISSUE THREAD

**Issue by Conor29134** [itdelatrisu/opsu#276]
Video:
https://www.youtube.com/watch?v=-fA6ZIxaxrA

**Comment by itdelatrisu** [comment]
Noted, thanks for the report and video.  (I probably won't have time to get to this for a while though.)

Self-note: linking yugecin/opsu-dance#31, but I don't like their solution (relies on too many globals).

**Comment by itdelatrisu** [comment]
Fixed in #299.
