### ISSUE TITLE
Options button should be shown on main menu

### ISSUE THREAD

**Issue by tpenguinltg** [itdelatrisu/opsu#279]
The button to show the options overlay should be shown in the main menu. If the user starts opsu! with an empty beatmap database (e.g. when starting for the very first time), there is no way to get to the options without downloading a beatmap first to get to the songs menu. One case where this matters is if a Linux user is having problems with the sound effects and needs to disable it (I ran into this issue when testing something else earlier). I'm sure there are other use cases for it, and if I'm not mistaken, osu! has the options overlay accessible from the main menu.

**Comment by flazep3** [comment]
Completely agree! Seems like nearly all of beatmap download servers cannot be downloaded using opsu! Since most of the server uses captcha now. Sad. Now I need to download beatmaps manually. Only Mnetwork works ;/

**Comment by 111116** [comment]
strange that it's still not implemented in 2019? I can press O to open the option menu, but that's not easy to figure out for all users.
