### ISSUE TITLE
[Feature Request] some things 

### ISSUE THREAD

**Issue by flazepe** [itdelatrisu/opsu#282]
Not forcing you but maybe you could implement one of the easiest things in the list:

1. Key input. [Implemented]

2. Greeting screen/sound like "Welcome to osu!". [?]

3. More skinning options. [?]

4. More mods. [?]

5. Updated UI [Implemented]

**Comment by flazep3** [comment]
Don't be mad, it's just a feature request. Feel free to do it or not. (That's what she said)
