### ISSUE TITLE
HEAD currently has no snaking sliders

### ISSUE THREAD

**Issue by GigabyteProductions** [itdelatrisu/opsu#286]
I've built from head in anticipation of testing #269 before it is released, and noticed sliders do not snake despite the setting. I have bisected it to two commits:
```
$ git bisect skip
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
0ad829189ca7972dbcea61381d0573b5088b68aa
3db9be9bbbfada52f380e0f9af278f3bf572a97a
We cannot bisect more!
```

**Comment by itdelatrisu** [comment]
Thanks for reporting!  Sorry for the late reply.
