### ISSUE TITLE
osz map can't load

### ISSUE THREAD

**Issue by aiwonanjing** [itdelatrisu/opsu#291]
Because of GFW and I'm in China, I don't have the right to use the online maps, so I download the maps from the official website of OSU!, but many maps can't be imported to the software, just say failed. Could you fix the bug? Could you give me a more convenient way to get the maps?

**Comment by itdelatrisu** [comment]
I have no idea what the bug is if you don't include any details... please post your error log (`.opsu.log`) and at least the beatmap names/IDs.  And no, I'm not going to write a way to download maps from the osu! servers (see #277 for related discussion).

**Comment by aiwonanjing** [comment]
The log said
Warn: Failed to open connection. 
java.io.IOException: Negative content length
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:242)
which seems to declare why I can't connect to the server.

**Comment by itdelatrisu** [comment]
Most of the servers no longer work, there's nothing I can do.  But I don't know what you mean by "many maps can't be imported to the software, just say failed".

**Comment by aiwonanjing** [comment]
This is one head of OSU file I can't see from the play list by the software, but it's true that it has been exacted by OPSU.
AudioFilename: audio.mp3
AudioLeadIn: 0
PreviewTime: 93749
Countdown: 0
SampleSet: None
StackLeniency: 0.7
Mode: 3
LetterboxInBreaks: 0
SpecialStyle: 0
WidescreenStoryboard: 1

[Editor]
DistanceSpacing: 0.8
BeatDivisor: 16
GridSize: 32
TimelineZoom: 1.1

[Metadata]
Title:Yume no Tobira
TitleUnicode:Yume no Tobira
Artist:Sakurauchi Rikno (CV.Aida Rikako)
ArtistUnicode:Sakurauchi Rikno (CV.Aida Rikako)
Creator:[-AL-]
Version:Hard
Source:Love Live School Idol Sunshine
Tags:Love Live School Idol Sunshine, Yume no Tobira, Sakurauchi Riko
BeatmapID:1265039
BeatmapSetID:598437

**Comment by aiwonanjing** [comment]
In the osz file, it only has three files, the music, the background picture and the map(osu) file.

**Comment by itdelatrisu** [comment]
That's an osu!mania beatmap; this project only implements osu! standard mode.  Closing this issue, feel free to add other comments.
