### ISSUE TITLE
unable to download any songs at all

### ISSUE THREAD

**Issue by AsukiChan** [itdelatrisu/opsu#294]
i just get a fking msg saying error failed due to a connection error but i have full perms and have given it all perms on my network EXPLAIN please this is on Android version 6.0.1

**Comment by itdelatrisu** [comment]
The download servers are down.

**Comment by AsukiChan** [comment]
ok thnx

**Comment by jeroen7s** [comment]
when will they come back up?

**Comment by itdelatrisu** [comment]
Probably never. (I don't run them.)

**Comment by AsukiChan** [comment]
ok :(
