### ISSUE TITLE
Song keeps repeating itself on main menu

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#30]
As the title explains, if the song ended, instead of playing the next random song, it just repeats the same song over and over again.

Just found this from fluddokt's opsu-android but i think it also happens at opsu! as well (since it have almost the same code). 

Will update after i have access to my laptop to double confirm this.

**Comment by itdelatrisu** [comment]
I tried fixing this earlier with MusicListeners for the end of tracks, but kept running into crashes with multithreading.  Not really sure how to fix this using slick's libraries.

**Comment by chong601** [comment]
I think you can just borrow the code for the Next song thing? Just a rough guess

**Comment by itdelatrisu** [comment]
Fixed by fluddokt in #38.  Will follow up shortly.
