### ISSUE TITLE
Offsync and S-Pen issues

### ISSUE THREAD

**Issue by Drewdememer** [itdelatrisu/opsu#304]
Currently, it's literally unplayable because of very big offsync, fixing offset doesn't help.

Also, when im trying to play with pen, it changes local offset when im touching the screen.

Device: Samsung Note 10.1

**Comment by Lemmmy** [comment]
perhaps bring the issue to [fluddokt/opsu](https://github.com/fluddokt/opsu/)? fluddokt maintains the andriod versions of the game.
