### ISSUE TITLE
Minimized opsu! "stops" the music

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#32]
(invalid this if this is intended)
As the title says, minimizing opsu! will stop the background music (including when moving the window as well if not fullscreen)
Affects builds 0.6.0 till latest commit
Last version without this issue: 0.5.0

**Comment by itdelatrisu** [comment]
No idea it's even possible to fix this in slick/lwjgl.

**Comment by itdelatrisu** [comment]
Minimized window - fixed in #38.
Moving the window - as far as I know, not possible to fix.
