### ISSUE TITLE
Discord? Or other real-time development chat?

### ISSUE THREAD

**Issue by LovelyA72** [itdelatrisu/opsu#328]
Od we have a development discord? It will be very convenient if we have a real-time chat channel. 
![image](https://user-images.githubusercontent.com/29054052/31696762-10500e18-b3e6-11e7-9870-a2bc6ad2afe1.png)
osu!dev channel on Discord

**Comment by itdelatrisu** [comment]
Nope. Pretty sure it'd be empty, especially since this isn't exactly in active development anymore...

**Comment by LovelyA72** [comment]
At least we can chat and work on our new wiki 😃 
we need a lot in our wiki(such as translate). Currently i am working on osu!wiki's i18n (English to Chinese part). and i highly feels that a real-time chat is very convenient.

**Comment by Lemmmy** [comment]
I find that Discord chats often lead to unproductivity and drama. I think GitHub Issues works fine.

**Comment by LovelyA72** [comment]
oh yeah... i agree with you.
