### ISSUE TITLE
Long startup

### ISSUE THREAD

**Issue by Lucki** [itdelatrisu/opsu#34]
With lots of beatmaps, opsu takes really long time to start.
Right now with 2200 different songs (6200 Beatmaps) in `/Songs/`, opsu needs about 30 seconds to start, according to it's own ingame-timer.

**Comment by itdelatrisu** [comment]
This should've been resolved in recent commits with the beatmap cache.  You can also just press 'esc' to stop loading beatmaps at any time.

**Comment by Lucki** [comment]
It's with the latest commit. Do I have to activate the cache somewhere?
~~~
lucki@Archlinux ~ % pacman -Q opsu-git
opsu-git 0.6.0.r36.g078b765-1
~~~

**Comment by itdelatrisu** [comment]
Is there a file ".opsu.db" being generated?  With about 1k beatmaps, my program loads in under 1 second...

**Comment by Lucki** [comment]
Yes, it's in `~/.local/share/opsu/.opsu.db`.  File size is `5,4 MB`. Maybe opsu regenerate it at every start because it can't find the existing database?

**Comment by Lucki** [comment]
So, I've imported some beatmaps (5000 songs 16000 bm now) and deleted the cache. (`.opsu.db`)

1. start: `1m50s`
2. start: `3m`
3. start: `3m`

Then I deleted the cache again:

1. start: `20s`
2. start: `3m`
3. start: `3m`

And a third time to be sure, deleting the cache every time:

1. start: `10s`
1. start: `10s`
1. start: `10s`

The cache was every time `19,5MB`.
It's actually faster to delete the cache every time?

**Comment by itdelatrisu** [comment]
Okay, I'll take a look at what I can do... though it's sort of hard to test since it's actually faster on my own computer.  My only guesses are that (1) the table isn't indexed and (2) `SELECT` queries are done individually instead of in batch.

**Comment by itdelatrisu** [comment]
Any improvements with the last commit (5e9d9a4)?

For reference, on my (Windows) computer with about 1000 beatmaps:
* Without cache: `1.6s`
* With cache (before update): `0.9s`
* With cache (after update): `0.5s`

**Comment by Lucki** [comment]
1. without cache: `3m`
2. with cache: `4s`
3. with cache: `4s`

Much better :smile:

**Comment by itdelatrisu** [comment]
Great!  Thanks for finding this out!

**Comment by itdelatrisu** [comment]
I cut my loading time in half again with f9878f4 - is everything still working on your end?

**Comment by Lucki** [comment]
Yes, without cache `3m`, with cache `2s`.
:+1:
