### ISSUE TITLE
Someone released an android version of opsu! on Play Store

### ISSUE THREAD

**Issue by flaze216** [itdelatrisu/opsu#340]
Not sure if you know this and guess what, he didn't credit you nor fluddokt. He even made his own repo here: https://github.com/AnirudhRahul/opsu

Since this is open-source, he could at least credit you and fluddokt for the code.

Play Store link: https://play.google.com/store/apps/details?id=fluddokt.opsu.android&hl=en

My question is, do you approve this?

**Comment by itdelatrisu** [comment]
It seems like proper credit is given -- there are links to the source repositories, no removal of credits in the fork, and no modifications to the authorship in-game (https://github.com/AnirudhRahul/opsu/blob/master/src/itdelatrisu/opsu/OpsuConstants.java).  And I appreciate that their fork is also open-source.

I don't really care what people do as long as it's not violating the license (GPL3). I can't speak for fluddokt though.
