### ISSUE TITLE
[PSA] opsu! in Google Play.

### ISSUE THREAD

**Issue by RaikireHiuduo** [itdelatrisu/opsu#346]
(Maybe a false alarm at my part since I am out of the loop but still, do check it out)

Link: https://play.google.com/store/apps/details?id=fluddokt.opsu.android&hl=en

So, I just opened my Google Play and I saw above. Going in and checking the commit list of the shows me this: https://github.com/AnirudhRahul/opsu/commits/opsu-Android

![o](https://user-images.githubusercontent.com/24448073/33860812-8edea302-df15-11e7-94df-ad3bfb407353.png)

Seems like a direct fork from `fluddokt/opsu` (which is a working Android branch) and then a quick push to the Google Play under the user name.

I assume you already know this but I am posting this for the sake of clarity.

Also, reddit post: https://www.reddit.com/r/osugame/comments/7f2kay/opsu_now_on_google_play_store/

![image](https://user-images.githubusercontent.com/24448073/33861080-d341a28c-df16-11e7-8f9a-6b23c5566ab5.png)

Close this issue if it is a false alarm (assuming fluddokt is actually using another name just for Google Play, which I am doubting now).

Thank you.

**Comment by Lemmmy** [comment]
Duplicate of #340 and #343. This is an issue with fluddokt/opsu anyway.

**Comment by RaikireHiuduo** [comment]
OK. Thanks for the heads up.

Closing now.
