### ISSUE TITLE
fd

### ISSUE THREAD

**Issue by Negative31** [itdelatrisu/opsu#350]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Windows 7 (x86)
**JRE:** 1.8.0_121
**OpenGL version:** 4.5.13397 Compatibility Profile Context 15.200.1046.0 (ATI Technologies Inc.)

**Comment by Lemmmy** [comment]
thank you
