### ISSUE TITLE
Sound bug

### ISSUE THREAD

**Issue by StRikErFlex** [itdelatrisu/opsu#351]
so i installed the game today in the appstore, i imported some maps but when i want to play them they sound like if i have 5 fps or smth (even the main menu song)
edit: in the under right corner the fps shows 60 but the music laggs with the game (dont know how to explain correctly in english)

**Comment by Lemmmy** [comment]
> appstore
Is this an issue with [fluddokt/opsu](https://github.com/fluddokt/opsu)

**Comment by StRikErFlex** [comment]
i dont really have a overview of github, so what exactly means this?

**Comment by Lemmmy** [comment]
I mean you are posting the issue in the wrong place. This is for the desktop version of opsu!.

**Comment by StRikErFlex** [comment]
oh ok sry
