### ISSUE TITLE
Just letting you guys know, someone uploaded this to the Google Playstore.

### ISSUE THREAD

**Issue by MegaFish0527** [itdelatrisu/opsu#353]
I don't think it was one of the devs here, so I'm just letting you guys know.

**Comment by Lyonlancer5** [comment]
Duplicate of #346 
See [here](https://github.com/itdelatrisu/opsu/issues/346#issuecomment-350904627)

**Comment by itdelatrisu** [comment]
Yup, this was reported earlier but thanks for the concern.
