### ISSUE TITLE
Replay Not Saved in Opsu v0.16.0b

### ISSUE THREAD

**Issue by Exaridous** [itdelatrisu/opsu#358]
It didn't saved my replays in opsu so i would like to suggested to fix this for enjoy full game in opsu!.Thank You very much.

**Comment by tpenguinltg** [comment]
Please open an issue in [fluddokt/opsu](https://github.com/fluddokt/opsu/issues). v0.16.0b is a release from there.

**Comment by itdelatrisu** [comment]
Confirming it's fine on 0.16.0.

**Comment by Exaridous** [comment]
Thanks :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
