### ISSUE TITLE
Spinner skins long loading time

### ISSUE THREAD

**Issue by Lucki** [itdelatrisu/opsu#36]
Some skins for the spinner takes long time to load, so that the spinning-time is almost over when the spinner appears on screen.

**Comment by itdelatrisu** [comment]
All images are loaded before the game begins, so this is invalid.

There are definitely issues with the spinners not appearing fast enough though, but i can't figure out when to show them.

**Comment by Lucki** [comment]
Ok, I've recognized this with different skins. Could be something else.
