### ISSUE TITLE
Getting a java error

### ISSUE THREAD

**Issue by Colorblind22** [itdelatrisu/opsu#368]
I downloaded the game a few days ago and have been enjoying it. Please help!

Can't figure out how to upload image on mobile, but I'll just say the gist here

Its saying failed to create slider and then throwing out a ton of java errors. I'm not well versed in java so I have no idea what it means.

**Comment by Lemmmy** [comment]
Can you post the full error log?

**Comment by Lemmmy** [comment]
Also - if you are on Android, the issue should be taken to [fluddokt/opsu](https://github.com/fluddokt/opsu) instead.

**Comment by itdelatrisu** [comment]
Closing since no details were provided. @Colorblind22, if you have the logs (a file called `.opsu.log`) then please upload and re-open this issue. Thanks!
