### ISSUE TITLE
Song loading/reloading issue

### ISSUE THREAD

**Issue by WilkerS1** [itdelatrisu/opsu#370]
sometimes when i retry a song multiple times using retry, the playfield  appears normally but the song doesn't start nor is it played. when i hit "Skip?" it also doesn't start, leaving the hp bar filling up repeatedly. it goes back to normal when i load another song by just selecting it in the menu and then the previous again.

**Comment by tpenguinltg** [comment]
Can you please give us more details? Things like opsu! version, Java/JRE version, and OS? If it happens for a specific song, please also include what song it is.

**Comment by WilkerS1** [comment]
(i am not aware of how to find the java version)
opsu! version 0.16.0b
Android 5.1.1

it happens in most songs i fail/retry repeatedly. from ENTRANS OF DA JUNGLE to The Big Black, Image Material, sans., Igtus Figitus, etc.

**Comment by tpenguinltg** [comment]
Ah, this is the Android version. Sorry, you'll have to open an issue in [fluddokt/opsu](https://github.com/fluddokt/opsu); we don't provide support for that version here.

**Comment by WilkerS1** [comment]
understood. i will open it there. thank you
