### ISSUE TITLE
error in installation page in our wiki

### ISSUE THREAD

**Issue by LovelyA72** [itdelatrisu/opsu#377]
I found this error while I translating that page:
inside Windows section, we can see that:

Run opsu! from the working directory (if _osu!_ in `G:\(directory name)`, then put `opsu!.jar` into _osu!_ folder located in `G:\`).

but the problem is we know that opsu! will not work if the folder name contains "!", so I suggest we can add a note to notify the reader.

link: https://github.com/itdelatrisu/opsu/wiki/installation

**Comment by tpenguinltg** [comment]
Please go right ahead and make any changes you think are appropriate. These wiki pages so far haven't really been worked on since they've been imported from the osu! wiki, so there are a lot of things that are outdated.

**Comment by LovelyA72** [comment]
edited ;)
