### ISSUE TITLE
java.lang.NoSuchMethodError:java.util.Locate.forLanguageTag

### ISSUE THREAD

**Issue by ThePotatoDuke** [itdelatrisu/opsu#380]
This error shows up when I complete a song. Also hit sounds disappeared

**Comment by Lemmmy** [comment]
Can you please provide the full error/crash report? Additionally, your game version, operating system, and Java version would be helpful.

**Comment by Lyonlancer5** [comment]
> Locate.forLanguageTag

Did you mean `Locale.forLanguageTag`?
May be Android-related, as most of these issues arise in the Android port with this stack trace:

```
java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335)
```

and [this](https://github.com/fluddokt/opsu/blob/master/src/itdelatrisu/opsu/replay/Replay.java#L335) is the line in question, which isn't present [here](https://github.com/itdelatrisu/opsu/blob/master/src/itdelatrisu/opsu/replay/Replay.java#L328).

**Comment by Lemmmy** [comment]
Android issues go towards https://github.com/fluddokt/opsu

**Comment by ThePotatoDuke** [comment]
Sorry I meant java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335) Sorry again :/
