### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by Alib234** [itdelatrisu/opsu#384]
Is there an reset password for an account because i made one in opsu android and i think i mistyped my password my account is well Alib234 and i cant get in it because wrong pass ;(

**Comment by Lemmmy** [comment]
This is the repository for the Desktop game. Perhaps you want [fluddokt/opsu](https://github.com/fluddokt/opsu) or [opsu-Android](https://github.com/AnirudhRahul/opsu-Android) (play store version).

**Comment by Alib234** [comment]
oh ok sorry but it doesn't say anywhere that this is a windows specific git hub

**Comment by Lemmmy** [comment]
![](https://shitty.download/BVla.png)
