### ISSUE TITLE
Cannot preview songs before downloading

### ISSUE THREAD

**Issue by TwitchinAllDay** [itdelatrisu/opsu#385]
When I initially downloaded opsu on my android, I was able to preview songs before I would download them. However, now when ever try to preview a song, the background music stops and there is silence. For every song I try to preview. Is this a bug, and if so is there a fix?

**Comment by tpenguinltg** [comment]
Please open an issue in [fluddokt/opsu](https://github.com/fluddokt/opsu/issues) (or [AnirudhRahul/opsu-Android](https://github.com/AnirudhRahul/opsu-Android) if you got it from the Play Store). We don't support the Android version here.

**Comment by itdelatrisu** [comment]
Confirming it still works fine on desktop.

**Comment by TwitchinAllDay** [comment]
On my pc, it won't start up. Its stuck in an endless "updating" loop

Sent from Yahoo Mail on Android 
 
  On Fri, Apr 20, 2018 at 8:36 PM, Jeffrey Han<notifications@github.com> wrote:   
Closed #385.
