### ISSUE TITLE
Local offset -5 

### ISSUE THREAD

**Issue by chutchatut** [itdelatrisu/opsu#392]
Local offset -5 every time I touch the fingerprint scanner. Pixel 2 on Android P DP2.

**Comment by chutchatut** [comment]
Sorry on wrong thread.

**Comment by tpenguinltg** [comment]
If this is still an issue or if you have any issues with the Android version in the future, please open an issue in [fluddokt/opsu](https://github.com/fluddokt/opsu/issues) (or [AnirudhRahul/opsu-Android](https://github.com/AnirudhRahul/opsu-Android/issues) if you got it from the Play Store). We don't support the Android version here.
