### ISSUE TITLE
opsu freezes when trying to load beatmap at song selection.

### ISSUE THREAD

**Issue by takase1121** [itdelatrisu/opsu#395]
This is probably because of my really crappy hard disk, but opsu freezes when I click on one of the beatmaps at the song selection menu to play. The lag "level" varies, sometimes it raise "Not responding" window on Windows. Any ideas to fix this?

**Comment by tpenguinltg** [comment]
Does this happen on any specific beatmaps? It might happen on some of the Aspire maps.

**Comment by takase1121** [comment]
Can't found the issue anymore, I think this is my hard disk issue when trying to load too many stuff. The hard disk simply can't keep up because of paging and opsu loading data. I'm actually glad because this phenomenon is actually worse when I tried osu lazer out.
