### ISSUE TITLE
opsu crashed owo

### ISSUE THREAD

**Issue by takase1121** [itdelatrisu/opsu#397]
My opsu crashed just now, here's the log:
[hs_err_pid6368.log](https://github.com/itdelatrisu/opsu/files/2066568/hs_err_pid6368.log)

opsu version: 0.16.0

**Comment by tpenguinltg** [comment]
Do you remember what you were doing when the crash happened? Have you tried updating your version of Java?

**Comment by takase1121** [comment]
I was in the middle of a play, and I can't update my Java now because my internet is constrained by my data package.

**Comment by takase1121** [comment]
Found a way to update my Java version to 10.0.1 and the bug is gone. Thanks!

**Comment by tpenguinltg** [comment]
I didn't realize Java 10 was already out. Note, though, that we only officially support 7 and 8 right now, but it might still work. You're welcome to help us achieve compatibility, if you'd like.

**Comment by takase1121** [comment]
Sure, I'll notify you if theres any crashes or bugs that appear.
