### ISSUE TITLE
laggy result screen

### ISSUE THREAD

**Issue by takase1121** [itdelatrisu/opsu#400]
Every time I done playing a beatmap, the result screen is really laggy on my laptop. The FPS dropped to ~10. Is this supposed to be normal (considering I have a really bad laptop) or its a bug?

**Comment by itdelatrisu** [comment]
Yeah, a lot of stuff happens here (notably, compressing/saving the replay), which could slow down the game rendering logic if your CPU is slow. I think we could technically move that to a background thread (nothing depends on it), but it probably isn't going to happen.
