### ISSUE TITLE
No volume control

### ISSUE THREAD

**Issue by professorg** [itdelatrisu/opsu#405]
There are no options within the application to change the volume (or any settings). The application is very loud by default and I have no per-application volume mixer.

**Comment by yugecin** [comment]
In the song-selection screen you can click the 'other options' button to open the option menu and change audio settings.
Alternatively, you can press CTRL+O in either the main menu or song-selection screen to open the options menu.

![](http://pokit.org/get/img/d76a6ae1df4ad73d93752b5124c5bd3a.jpg)

**Comment by tpenguinltg** [comment]
You can also use the scroll wheel on the main menu and during a song to change the volume.

If there's an action point here, it's that it should be documented somewhere (probably in the wiki). Do you think we need to do that?

**Comment by yugecin** [comment]
You can also change the volume on the song-selection screen using the scroll wheel if you hold ALT.

All this behavior is the same as in osu!, except that opsu! does not have an option button in the main menu, and that there's an option button in the song-selection screen. This is noted in the wiki at the [options page](https://github.com/itdelatrisu/opsu/wiki/options), but it might be useful for people that never played osu! before.

**Comment by LovelyA72** [comment]
Chinese wiki translation updated√
