### ISSUE TITLE
About avatars in 0.16.1

### ISSUE THREAD

**Issue by LovelyA72** [itdelatrisu/opsu#410]
I want to create a wiki page about how to replace avatars in 0.16.1 via skin system. Since most of my friends like these avatars before 0.16.1. It will be both in English and Chinese.

**Comment by itdelatrisu** [comment]
Go for it. You probably know how it works, but for others - it's skinned the same way as the slider ball (`sliderbX.png`, where `X` is an incrementing number). Just add `userX.png` image(s) to your custom skin.

**Comment by LovelyA72** [comment]
Done~ And sorry for the late reply.

https://github.com/itdelatrisu/opsu/wiki/skin
https://github.com/itdelatrisu/opsu/wiki/skin-zh
