### ISSUE TITLE
Skin not loading?

### ISSUE THREAD

**Issue by Achelmic** [itdelatrisu/opsu#419]
I have turned an .osk to .zip and unzipped the skin to a folder, put the folder in the Skins folder, but it won't load correctly, 4 Errors pop up and the last one won't load at all, the four are 
**count1s.wav
count2s.wav
count3s.wav
gos.wav**
and the fourth one being "**soft-hitclap.wav**" where it won't freeze the launcher but it won't progress any further.

**Comment by tpenguinltg** [comment]
What are the errors that you're getting? What skin are you trying to use? Is this the same as #416? If so, please close this and continue discussion there.
