### ISSUE TITLE
Parsed 550 objects for beatmap 'Queen's Blade Spiral Chaos (Yousei Teikoku) - Gekkakou [Collab]', 551 objects expected.

### ISSUE THREAD

**Issue by Haringat** [itdelatrisu/opsu#420]
**Version:** 0.16.1
**Build date:** 2018-08-08 00:33
**OS:** Linux (amd64)
**JRE:** 10.0.2
**OpenGL version:** 4.6.0 NVIDIA 396.45 (NVIDIA Corporation)
**Error:** `Parsed 550 objects for beatmap 'Queen's Blade Spiral Chaos (Yousei Teikoku) - Gekkakou [Collab]', 551 objects expected.`

**Comment by tpenguinltg** [comment]
We don't officially support Java 10, but that's probably not the issue here.

Was there a stack trace?

**Comment by Haringat** [comment]
I didn't see one. However, I hadn't started opsu via console and since it crashed right after showing the error dialog I can't be sure.
When I come home I will check if there is a stacktrace as well as whether or not this occurs in Java 8 and 9.

**Comment by tpenguinltg** [comment]
If there was an error, it should be logged to `.opsu.log` file in your config directory, which is wherever the JAR file is if you got it from the GitHub releases, or `~/.config/opsu/` if you built with `-DXDG=true` (which is the case if you got it from the AUR).

Note that we also don't officially support Java 9, though it'll probably also still work.

**Comment by Haringat** [comment]
Looks like Osu! used an unsigned byte for that value while Opsu! uses Java's byte (which is signed). Thus values >= 128 cause an error. I fixed it and will submit a PR.
