### ISSUE TITLE
General improvements to opsu! to match upstream game (osu!)

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#43]
I have assigned myself to this issue (no ETA on when it can be done for now)
Checklist:
- [x] Split updateAndRender to use org.lwjgl.Display.update() and org.lwjgl.Display.sync(FPS) to ensure use of offscreen buffer to remove dependency of high fps (superseded from #40) (UPDATE: game choppy has been fixed, marking this as completed for now, but the development is still underway)
- [ ] Attempt to match the gameplay logic with osu! as closely as possible
- [ ] Fix scoring issue with opsu! displaying more score than osu! (screenshots will be added later for comparison)
- [ ] Remove dependency to FPS completely for **all** animations in opsu! (related to checklist 1)
- [ ] Allow usage of skin.ini to allow more skin customizations (focuses more on skin versions, currently in progress)

Unrelated to osu! features
Package Java Runtime Environment with opsu! to allow running on machines without JRE (scrapped because of non-portability issues, requiring **three** separate builds)

Any other osu! related things (that I can't think of for now) that is missing in opsu! , please post here! (I will try to make it as long I have the time and ability to do it, currently getting used to Maven goals and LWJGL APIs)

Things that I will not do (due to certain reasons)
- Online capability

Things that I will not do (because of ability issues)
- Implement DirectX (sounds like a herculean task for a non-Windows runtime)

@itdelatrisu: can you put me to the assignee and (optional) set milestone to 1.0 maybe?

**Comment by Jackall4BDN** [comment]
And here i am, back again!
Now that i have played it a bit, i gotta say, good clone considering how (compared) little time has went into its development.
BUT two things are a major pain for me right now:
-The spinners are treated way to different difficulty-wise to actually do them on higher difficulties
-Audio-Offset-Callibration is REALLY wierd when it comes to precision, i gotta set it up to about -160 ms to get it fit the notes and it still seems to vary from song to song, while in normal osu (or every other musicgame i play) i gotta set it to -50ms tops and just one time and it would stick

**Comment by FenekAlfa** [comment]
> Attempt to match the gameplay logic with osu! as closely as possible

If this means autofail for some maps, removing custom AR/CS/etc. and locking K1&M1/K2&M2 together then it's a terrible idea. IMO the biggest advantage of opsu! it NOT being osu!.

**Comment by chong601** [comment]
>If this means autofail for some maps, removing custom AR/CS/etc. and locking K1&M1/K2&M2 together then it's a terrible idea. IMO the biggest advantage of opsu! is NOT being osu!.

don't worry, none of the abovementioned will be happening
(to be honest, i do want to close this since i don't have enough expertise to do all of those D:)

**Comment by Jackall4BDN** [comment]
That's a real shame, this project was soooo promissing, and it will take some serious time, before someone will pick this up...

**Comment by LemonLake** [comment]
I don't think you comprehended the above post.
Regardless, the audio offset bug is being fixed in #78. As for the spinner
bug, it has been reported and it is being looked into. They are not huge
problems that will take decades to fix.

**Comment by LemonLake** [comment]
Audio offset bug being worked on in #78.
Slider bug has been noticed #67.

**Comment by itdelatrisu** [comment]
>Fix scoring issue with opsu! displaying more score than osu! (screenshots will be added later for comparison)

Do you have any examples?  Otherwise, I'll close this since the other things you mentioned are complete or aren't really "issues".  I don't think it makes sense to package JRE with this, either.

**Comment by chong601** [comment]
osu! score:
![osu! score](http://puu.sh/ioy14.jpg)

opsu! score:
![opsu! score](http://puu.sh/ioybS.jpg)

kinda busy with real life so unable to update them D:

**Comment by itdelatrisu** [comment]
Yeah, no problem -- thanks for taking the time to post that.  Any idea what might be causing this? x.x

**Comment by chong601** [comment]
my rough guess is probably the formula for total score isn't correct (just not quite sure where)

**Comment by fluddokt** [comment]
Its the Difficulty Multiplier in the score formula.
You can try my replayTest branch, its gets pretty close for some beatmaps.
However it might screw up your opsu_scores.db after running it.

**Comment by itdelatrisu** [comment]
Yeah, that's what I've been trying to figure out.  After looking at your changes, though, it looks like I was really far off... anyway, I'll commit the few updates I've made based on the osu! wiki (all lies, as you've noticed too XD), but I don't really know where to go from here.
