### ISSUE TITLE
Better Join PPY Team

### ISSUE THREAD

**Issue by hafizdkren** [itdelatrisu/opsu#430]
Hello. You had a nice project here. But i wanted you to join PPY team and make osu!lazer also make osu!stable on android. So you would get money by our support and you can open in-game purchase for support osu!. So everyone win wanna on pc or android. If somebody interested with this idea too but wanna on apple device at least it's kinda copy paste the code and make to be apple app. Sorry for my bad grammar. I hope this message can make better for you and Dean Herbert aka PPY

**Comment by Ndog41** [comment]
It would also be nice if there was an official osu! Linux client, simply so that we could interact with the leader boards of everyone playing on Windows.

**Comment by Goky979** [comment]
Or why not message osu!evolution developers for a shared leaderboard if thats possible?

**Comment by Lemmmy** [comment]
@Ndog41 osu! runs perfectly fine in Wine, and has done for many years. It is as "official" as it gets right now, and the leaderboards work fine. Several players in the top 200 are also Linux users.

**Comment by Ndog41** [comment]
Didn't know that. Guess I'll have to try that.
