### ISSUE TITLE
Bugs and possible new features report

### ISSUE THREAD

**Issue by TheFantasticLoki** [itdelatrisu/opsu#433]
First i will list the bugs i have found so far in my 4 hours of using the client.

========================
**BUGS** 
========================
When trying to change sorting mode, menu does not appear and it goes into search mode.
-----
Not adapting to new aspect ratios such as 18:9 for the Note 8
-----
Unable to change screen resolution. Reverts back to original resolution on game launch.
-----
Cursor lags behind a little in game when using s-pen while normal os cursor for s-pen does not.
-----
Downloaded beatmaps do not import properly after changing beatmap location
-----
Missing beatmaps on download section
-----
Unranked games can still be posted to leaderboards
========================
**POSSIBLE FEATURES** 
========================
Ability to change sorting in cfg file
-----
Compatibility with 18:9 aspect ratio screens
========================
Phone Details
========================

DEVICE
Model: SM-N950U (greatqltesq)
Manufacturer: samsung
Baseband Version: N950USQU5CRG7
RIL Version: Samsung RIL v4.0
Build Number: R16NW.N950USQU5CRG7
Bootloader: N950USQU5CRG7
Java VM: ART 2.1.0
OS Version: O (8.0.0)
SDK: 26

DISPLAY
Resolution: 1440x2678 pixels
Software Density: 560 dpi
Refresh Rate: 60 Hz

PROCESSOR
CPU Architecture: AArch64 Processor rev 1 (aarch64)
Board: msm8998
Chipset: Qualcomm Technologies, Inc MSM8998
Cores: 8
Clock Speed: 1171 MHz - 2361 MHz
Instruction Sets: arm64-v8a
CPU Features: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU Governor: interactive
Kernel Version: 4.4.78-13949550
Kernel Architecture: aarch64

GRAPHICS
Renderer: Adreno (TM) 540
Vendor: Qualcomm
OpenGL Version: OpenGL ES 3.2

RAM
Total: 5225 MB
Java Heap: 256 MB

STORAGE
Internal: 52.9 GB
External: 58.2 GB
========================

-_The Fantastic Loki_

**Comment by tpenguinltg** [comment]
Thanks for the detailed specs.

Sorry to say this, but please open an issue in [fluddokt/opsu](https://github.com/fluddokt/opsu/issues) (or [AnirudhRahul/opsu-Android](https://github.com/AnirudhRahul/opsu-Android/issues) if you got it from the Play Store). We don't support the Android version here.
