### ISSUE TITLE
Failed to start new process.

### ISSUE THREAD

**Issue by SilverFox41** [itdelatrisu/opsu#447]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (amd64)
**JRE:** 1.8.0_73
**OpenGL version:** 3.0 Mesa 18.0.5 (X.Org)
**Error:** `Failed to start new process.`
**Stack trace:**
```
java.io.IOException: Cannot run program "java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at itdelatrisu.opsu.downloads.Updater.runUpdate(Updater.java:323)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 2 more
```

**Comment by tpenguinltg** [comment]
Sorry for the delay.

How did you install opsu!? How are you running it? Is `java` in your `PATH`?

**Comment by Ndog41** [comment]
I installed it using Lutris (the 64-bit version of opsu!.) Here's a link to the page. https://lutris.net/games/osu/ I was running it through Lutris's front end, and I don't know what you mean by "Is java in your PATH."

**Comment by tpenguinltg** [comment]
Sounds by a Lutris problem. You should try asking in their [support forum](https://forums.lutris.net/).

> I don't know what you mean by "Is java in your PATH."

`PATH` is an environment variable that contains a list of directories. If a program is in one of those directories, you can run that program just by giving the name of that program without a leading path. In this case, to call `java` without a path like we do, `java` has to be in a directory in your `PATH`. You can check by doing `which java` in your terminal, and it should give you the full path to the executable.

However, programs running other programs can set their own `PATH` variable, so it's possible that Lutris may be setting its own `PATH` before calling opsu! that doesn't include your Java directory.
