### ISSUE TITLE
Sliders won't load in properly

### ISSUE THREAD

**Issue by OfficialBirb** [itdelatrisu/opsu#456]
![screenshot_2018-11-16-22-06-40](https://user-images.githubusercontent.com/45113978/48655957-b4d1c480-e9ec-11e8-8b4f-5c5336643f17.png)
So the sliders won't load in i've redownloaded Opsu!  but the sliders won't load in!
Help!

**Comment by tpenguinltg** [comment]
This doesn't look like stock opsu!. What front-end are you using?

This also looks like it's specific to a beatmap. Which beatmap are you experiencing this issue with? Is it an Aspire map by any chance?

In the future, please include information such as your OS, your Java version, and your opsu! version. You can copy that info to your clipboard by clicking on the GitHub icon in the corner of the main screen and selecting "Copy Debug Info".

**Comment by OfficialBirb** [comment]
i am using opsu version 0.16.0b
all beatmap sliders won't load in.

**Comment by tpenguinltg** [comment]
0.16.0b is the Android version, which we don't support here. Please open an issue in [fluddokt/opsu](https://github.com/fluddokt/opsu/issues) (or [AnirudhRahul/opsu-Android](https://github.com/AnirudhRahul/opsu-Android/issues) if you got it from the Play Store).

**Comment by OfficialBirb** [comment]
Thanks
