### ISSUE TITLE
Infinite Song Reload Dialog

### ISSUE THREAD

**Issue by abalabahaha** [itdelatrisu/opsu#46]
After completed download of a beatmap using the in-game downloader, if f5 is pressed and the refresh dialog pops up, **clicking** either cancel or refresh button results in another popup after the refresh/current dialog closes. Using keyboard 1/2/esc will not result in a repeat dialog.
Ubuntu 14.04 + OpenJDK 1.7.0_75

**Comment by itdelatrisu** [comment]
I couldn't reproduce this.  Here were the two scenarios I tried:

1. Download a beatmap, wait for it to be 100% complete, then click "import".  Import is successful.  Go to song menu, click F5, hit either ok/cancel.  Works as intended.
2. Download a beatmap, wait for it to be 100% complete.  Go to song menu, click F5, hit either ok/cancel.  Import is successful, works as intended.

I'm using JDK 1.7.0_75 in Windows, though I wouldn't know why this would be OS-dependent.  Do you have any more information?  Does this always happen?

**Comment by abalabahaha** [comment]
Funny enough, it seems to be inconsistent now. But, when it does happen, it's when I **click** one of the buttons on the F5 menu in the song selection screen, new beatmap unnecessary. I think this can be set aside for now, as its inconsistent and could be caused by a number of factors (disk IO bottlenecking, cpu load, linux/Ubuntu, OpenJDK)

**Comment by chong601** [comment]
try check the <opsu! root folder>/SongPacks and see whether is there any files in it? That may cause the infinite reload issue...
