### ISSUE TITLE
Crash: Inconsistency detected

### ISSUE THREAD

**Issue by sbrl** [itdelatrisu/opsu#463]
I've recently upgraded my laptop from Ubuntu 18.04 to Ubuntu 18.10. With it came an upgrade from Java 8 to Java 11, apparently - which appears to be causing Opsu! to crash with the following message:

```
Inconsistency detected by ld.so: dl-lookup.c: 112: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

1. Start your Ubuntu 18.10 machine.
2. Download the latest version of Opsu!
3. Try to run it in a terminal.

**Comment by tpenguinltg** [comment]
We don't officially support anything other than Java versions 7 and 8, though it may work on other versions. You can either write a wrapper script to start opsu! with Java 8, or you can try building it manually and see if that works for you if you'd like. The build instructions are in the [README](https://github.com/itdelatrisu/opsu#building).

This [Ubuntu forums thread](https://ubuntuforums.org/showthread.php?t=2403730) suggests that a rebuild should do the trick.

**Comment by sbrl** [comment]
I'm using _Lutris_, so I have just configured it to start it with Java 8 explicitly, which appears to function as a temporary workaround.

I'm not well-versed in building Java programs, so I'm unsure how to follow those instructions.

**Comment by tpenguinltg** [comment]
That will probably serve as a suitable semi-permanent solution until we figure out how to support newer versions properly.

As for building, these are the basic steps:
1. Clone the project somewhere
2. Install Maven or Gradle. It doesn't really matter which one; the project nominally uses Maven, but I use Gradle myself.
3. `cd` into the project.
4. Build the project as stated in the README.
    - If you installed Maven, run `mvn package -Djar`. This will compile a jar to `target/opsu-${version}.jar`.
    - If you installed Gradle, run `gradle jar`. This will compile a jar to `build/libs/opsu-${version}.jar`.
5. Do what you want with the jar file.

**Comment by sbrl** [comment]
Hey, thanks for the instructions! I installed maven with `sudo apt install maven --no-install-recommends` - as it only used 12MiB of extra disk space compared with ~197MiB (O.o).

However, when I try and run the resulting `jar`, I get this:

```
$ java -jar /tmp/opsu/target/opsu-0.16.1.jar
Inconsistency detected by ld.so: dl-lookup.c: 112: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
$ java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-2ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-2ubuntu1, mixed mode, sharing)
$ mvn --version
Apache Maven 3.5.4
Maven home: /usr/share/maven
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-13-generic", arch: "amd64", family: "unix"
```
```

**Comment by itdelatrisu** [comment]
Closing as we don't support anything above Java 8, and probably never will (too hard to get all the dependencies working).

**Comment by sbrl** [comment]
I see. Perhaps an alternative solution will pop up.

Thanks anyway :-)
