### ISSUE TITLE
can't start on android

### ISSUE THREAD

**Issue by 2439905184** [itdelatrisu/opsu#464]
I use opsu android and download some beatmaps but I just can't start play
Every time I touch play ,It says download some beatmaps to start.
please fix it

**Comment by UnderSampled** [comment]
When you download beatmaps, they will show up in the queue on the right side of the download page, but will not be automatically imported. To import them, you'll need to click the "import all" button at the bottom right of the page.

**Comment by 2439905184** [comment]
I import maps from osu droid 
And I can play now

**Comment by 2439905184** [comment]
I import maps from osu droid 
And I can play now

**Comment by 2439905184** [comment]
Will you support more languages?

**Comment by tpenguinltg** [comment]
@Lyonlancer5 was working on an internationalization framework a while back. It remains to be seen whether it will be completed, but then there's also the issue of translators.
