### ISSUE TITLE
opsu directly fails the fifth simultanous beatmap download. 

### ISSUE THREAD

**Issue by angjinhang** [itdelatrisu/opsu#47]
Like the title said the fifth simultanous beatmap download I'm trying to create fails instantly. No waiting list, no timeout error, nothing, just fails instantly. 

opsu 7.0, java 1.7.0_76 (Oracle JRE, not openjdk), Lubuntu 14.04

Screenshot here. 
![screenshot_20150312_224043](https://cloud.githubusercontent.com/assets/6135654/6620154/22b90f9c-c90a-11e4-83e0-3f128347a281.png)

After one of the downloads complete (that means it drops to 3 simultanous downloads), I can create another download that works again. 

Anything that causes this?

**Comment by itdelatrisu** [comment]
The downloader uses the Bloodcat server, which limits you to 4 concurrent connections; there's no such restriction in opsu! itself.  I suppose I could work around this, but I'd rather not.
