### ISSUE TITLE
Error while creating game container.

### ISSUE THREAD

**Issue by AndreySeVeN** [itdelatrisu/opsu#51]
**Version:** 0.7.0
**Build date:** 2015-03-09 00:40
**Error:** `Error while creating game container.`
**Stack trace:**
```
org.newdawn.slick.SlickException: Failed to initialise the LWJGL display
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:378)
	at itdelatrisu.opsu.Container.start(Container.java:64)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:165)
```

**Comment by chong601** [comment]
Sounds like a failed initialization of the Display part...
Try updating to the latest graphic drivers?

**Comment by itdelatrisu** [comment]
Does chong601's solution work?  Or do you have any more information (e.g. OS, architecture, etc.)?

**Comment by itdelatrisu** [comment]
I'll assume this was resolved.  Please re-open if it wasn't.

**Comment by AndreySeVeN** [comment]
this was resolved
