### ISSUE TITLE
[Question] Is the project dead?

### ISSUE THREAD

**Issue by kairusds** [itdelatrisu/opsu#544]

**Comment by UnderSampled** [comment]
Pretty much. There are no active maintainers, if that's what you mean. There are still users, and the source is open, so feel free to dig into the code and start fixing things. I'm not sure if @itdelatrisu watches pull requests anymore, so a fork may be necessary (@fluddokt's is a likely candidate).

The officially supported Osu!Lazer does kinda make this project redundant, though I think I still prefer Opsu.
