### ISSUE TITLE
Request - Images

### ISSUE THREAD

**Issue by ethanaobrien** [itdelatrisu/opsu#567]
Hello, My parents dont really allow anime and I am allowed to play this as long as there are no images. Could someone make an option in the menu that adds the option to disable ALL images at ALL times? (except things like buttons)

**Comment by Likver** [comment]
U can delete all pics of all beatmaps, i think this have not more updates

**Comment by ethanaobrien** [comment]
I have built and compiled my own opsu .jar archive
