### ISSUE TITLE
Ability to disable self-update

### ISSUE THREAD

**Issue by Lucki** [itdelatrisu/opsu#58]
I don't know, how other projects handle this, but as I have this packaged ([opsu](https://aur.archlinux.org/packages/opsu) and [opsu-git](https://aur.archlinux.org/packages/opsu-git/)), the game loads itself in the working-directory, which isn't useful at all. (restart spams the working dir, often your home. The next manual start loads the old version from the system.)

First a switch like the XDG-switch came into my mind, but maybe there's another better way I'm not aware of.

**Comment by itdelatrisu** [comment]
Okay, here's a proper solution:

* Upload two JARs per release, and if XDG is defined, download the XDG release.
* Save updates to the JAR directory instead of working directory (possible, but I don't know how to support both JARs and running from class files/maven).
* Overwrite the existing file (is this even possible if I only distribute one JAR?).

But that's a hassle, and I really can't think of a way to do the last part (also, it'd be confusing if e.g. the 0.8.0 update overwrote a file named `opsu-0.7.0.jar`).  An alternative is to just disable the updater if XDG is defined (probably 1 line of code).  Thoughts?

**Comment by Lucki** [comment]
That would work, but you forgot, that programs are executed at user level - so they are not allowed to overwrite system files.

**Comment by itdelatrisu** [comment]
Why would you need to overwrite system files?

**Comment by itdelatrisu** [comment]
Let me know if you have any other ideas.

**Comment by Lucki** [comment]
I can't reopen this issue, so I ping you @itdelatrisu …
I've accidently opened an old version of opsu! (0.10.1.r64 at commit 31d0c23) with XDG enabled and there is an auto updater popping up for the newer 0.11.0 version. Maybe there went something wrong over time? It's a bit hard to test, because there has to be an update available.

Also I've missed your question about the system files. The pkgbuild is a recipe for building this project into an package which is installable into the system. According to the guidelines the opsu.jar lies in `/usr/share/java/opsu/`. So it's accessible for every user on the system. But only the admin can make changes there. (This is where the local config for every user comes to play, XDG)
A self-updater would download into the current working directory and could be started. But it's at a place, only one user has access to. Furthermore if not specifically this downloaded version is started, the older system version gets started and is recognizing an update every time.
The intended way to update is, that with a new version the pkgbuild gets an update. The admin starts an system updater, which recognize this as an newer version and rebuilds the package - along with all other updates for the system - and installs it at the same place in `/usr/share/java/opsu/`. So it's an easy and central way to get a system up-to-date.
Please let me know, if there are any more questions or i'm unclear somewhere.

**Comment by itdelatrisu** [comment]
Ugh, sorry for all these issues.  It's fixed in 8cb796b, and that looks like the last reference to the system property (another leftover from removing JarSplice).  Thanks for the thorough explanation, that makes a lot of sense.
