### ISSUE TITLE
How do I enter fullscreen mode?

### ISSUE THREAD

**Issue by BarrelKnight723** [itdelatrisu/opsu#602]
I have installed opsu on linux thorugh the java file and couldn't find a fullscreen option. How do I enable fullscreen?

**Comment by yugecin** [comment]
Go to the options menu (from the button in the main menu, or the button in the song select menu, or press CTRL+O), and there should be a checkbox somewhere near the resolution/display settings.

**Comment by BarrelKnight723** [comment]
Ok that seems to have worked. Also how do I install custom beatmaps that I have downloaded?

**Comment by MFDaus47** [comment]
> Ok that seems to have worked. Also how do I install custom beatmaps that I have downloaded?

Idk how Linux work. But if you can, locate the folder opsu and then put your .osz file in the import folder

**Comment by BarrelKnight723** [comment]
Ok everything seems to work. I will close this issue now.
