### ISSUE TITLE
Default skin.ini?

### ISSUE THREAD

**Issue by MFDaus47** [itdelatrisu/opsu#604]
Does anyone know the default skin.ini in this application. Can't seem to find it anywhere. I need it for some reference for skinning

**Comment by yugecin** [comment]
You'll have to plow through this code to see the defaults: https://github.com/itdelatrisu/opsu/blob/28003bfbe5195a97c1d7135d6060d09727768aab/src/itdelatrisu/opsu/skins/Skin.java#L30-L194

**Comment by MFDaus47** [comment]
> You'll have to plow through this code to see the defaults: https://github.com/itdelatrisu/opsu/blob/28003bfbe5195a97c1d7135d6060d09727768aab/src/itdelatrisu/opsu/skins/Skin.java#L30-L194

I see. Thank you so much. I didn't thought it would be in there. Thanks👍
