### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by mshhlvxk** [itdelatrisu/opsu#610]
null

**Comment by mshhlvxk** [comment]
fix this

**Comment by swanserquack** [comment]
1. You can't just demand the owner of the repository to fix this. He hasn't made a commit in over 2 years so you saying fix this will not change anything.
2. If you are so desperate to get it fix then clone the repository and try to fix it yourself, you might learn something new along the way.
3. The repository owner is a human too, treat him with respect as well.

**Comment by mshhlvxk** [comment]
all i did was report an issue i'm not forcing him

**Comment by mshhlvxk** [comment]
dude i didnt know
