### ISSUE TITLE
Unsupported language of the currently used font shown as 'tofu characters'

### ISSUE THREAD

**Issue by flyingfeather1501** [itdelatrisu/opsu#65]
As title says. Those unsupported characters should be fallen back to use system font, make the problem able to be solved by installing correct fonts. 

![13](https://cloud.githubusercontent.com/assets/11722318/6900442/0be85b6e-d739-11e4-8086-95e246c7502e.png)
This is how it currently looks in opsu 0.8.0, beatmap: http://osu.ppy.sh/s/72943

![14](https://cloud.githubusercontent.com/assets/11722318/6900533/b09d462e-d739-11e4-81d0-bb680eb23950.png)
This is how the same beatmap looks in osu b20150305

**Comment by itdelatrisu** [comment]
Yeah, I noticed this earlier too.  Unfortunately I really don't know how to fix this... do you have any ideas?

**Comment by flyingfeather1501** [comment]
The only thing I can think of is to use a font that's big enough, or merge some fonts together into one file...  falling back to system's sans-serif seems impossible after actully looking into the code.

**Comment by iceblade112** [comment]
Wow, apparently I'm still here!

Hey, you should take a look at this, @itdelatrisu: https://www.google.com/get/noto/cjk.html

It's OTF, though.. does Slick not have an OTF handling class?

**Comment by itdelatrisu** [comment]
It doesn't; those were actually the first fonts I tried using, but Slick's font support is terrible.  Kochi Gothic is the best thing I could find.

**Comment by iceblade112** [comment]
@itdelatrisu I'm testing out Unifont, but it's extremely ugly... :(

**Comment by iceblade112** [comment]
For the most part, it kind works...

but that ugliness...
![ftm](https://cloud.githubusercontent.com/assets/1739197/6984928/ee7864dc-d9fb-11e4-8446-e16087c077da.png)

**Comment by itdelatrisu** [comment]
Well... I could add a font switching option and keep Kochi Gothic as the default, but it'd really bloat the file size... I don't know. x-x

**Comment by iceblade112** [comment]
@itdelatrisu Yeah :(
Unifont is around 11mb with all (most) glyphs, and adding that with Kochi Gothic would make opsu! really big. 20mb for just fonts? That's a LOT.

**Comment by itdelatrisu** [comment]
(If you're still around, let me know what you think of the new font!)

**Comment by iceblade112** [comment]
I wish the English font was Roboto :(
But Droid Sans works too!

**Comment by itdelatrisu** [comment]
I tried playing around for a bit, but I think it'd be too much of a hassle to use multiple fonts for English/CJK text, at least using Slick's font engine.  It's difficult to get consistent layouts on all resolutions if I switch between two fonts, and I can't think of an efficient way to check if every rendered string contains non-ascii glyphs (aside from just wrapping the `String` class).

I don't know if merging the TTF files is possible without losing any quality, but that seems like the only reasonable approach.

**Comment by flyingfeather1501** [comment]
DroidSansFallback looks fine to me... 
I was thinking converting Noto CJK to TTF, but realized that's still only CJK and wouldn't be much better than DroidSansFallback.

**Comment by itdelatrisu** [comment]
If you want to give it a shot, let me know how it turns out -- I'm not completely satisfied with Droid Sans, but I agree that it's definitely fine for now.

**Comment by flyingfeather1501** [comment]
I tried to convert it with FontForge by importing it and exporting as TrueType Font. It gave me a bunch of warning, and after ignoring all warnings it created the ttf, put it into the .jar and it is just like no font have been loaded. 
![untitled](https://cloud.githubusercontent.com/assets/11722318/7666279/60378962-fc12-11e4-8486-4e293d6978f4.png)

**Comment by iceblade112** [comment]
@flyingfeather1501 If you load the ttf in Windows Font Viewer (or your operating system's respective font viewer), do the glyphs look correct?
