### ISSUE TITLE
Exporting replay call seems to be quite expensive

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#66]
(tried this on opsu-android though, close this if you think this is more on opsu-android issue rather than opsu!, just wondering though :P)

On opsu!, exporting replays is rather speedy (no hiccups whatsoever)
But on opsu-android (especially really underpowered processors such as Intel Atom Z2520, common on Asus phones), exporting replays to disk uses quite a lot of CPU processing.

It is not very noticeable on PC (there's some huge CPU spikes for about a second) but due to their running nature of Android, this seems to cause some issues with performance since the replay will be exported **immediately** after the ranking screen is dismissed.

My rough guess is from the lag I got during gameplay, the thread priority of the export replay is as high as the song playing (song stutters for the duration of the export, usually about 5-10 seconds)

**Comment by itdelatrisu** [comment]
It might be due to the LZMA compression, which takes a lot of CPU.  opsu! currently performs medium compression, so I guess that can be reduced on phones... not sure what I can do in this repository though, since it seems to work fine on desktop platforms.

**Comment by chong601** [comment]
probably only affecting my phone though, since most of my friends playing the latest version (0.8.0a) doesn't experience that (and looks like compression isn't a thing that Intel Atom processors can handle properly D:)

**Comment by itdelatrisu** [comment]
Probably leaving the compression as is unless other people are also having performance issues.
