### ISSUE TITLE
Snaking sliders & hit animations

### ISSUE THREAD

**Issue by LemonLake** [itdelatrisu/opsu#70]
^

**Comment by itdelatrisu** [comment]
Feel free to submit a pull request for these; I probably won't have time to implement them for a while.  I'd hold off on snaking sliders until Bigpet finishes #64, though.

**Comment by LemonLake** [comment]
I'll look for time to do it

**Comment by LemonLake** [comment]
#71

**Comment by itdelatrisu** [comment]
I'm going to close this for now, since this isn't really a bug anyway.  Let me know if you're planning on doing the snaking sliders too.  Thanks again!
