### ISSUE TITLE
File not found: 'virtual'

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#72]
The latest commit (4eaf0b6a5482e4a8e075627cb3d231e7b0cecfd5) have the following errors in opsu!.log:
```
    Fri Apr 10 09:20:22 SGT 2015 ERROR:File not found: 'virtual'
    Fri Apr 10 09:20:22 SGT 2015 ERROR:File not found: 'virtual'
    Fri Apr 10 09:20:22 SGT 2015 ERROR:File not found: 'virtual'
    Fri Apr 10 09:21:15 SGT 2015 ERROR:File not found: 'virtual'
    Fri Apr 10 09:21:15 SGT 2015 ERROR:File not found: 'virtual'
```
This happens when loading maps from my osu! folder (contains ~30k of maps)

**Comment by itdelatrisu** [comment]
Looks like it's from the parser, and there's a beatmap specifying an audio file name 'virtual' that doesn't exist.  The relevant code:
```
case "AudioFilename":
	File audioFileName = new File(dir, tokens[1]);
	...
	if (!audioFileName.isFile()) {
		// try to find the file with a case-insensitive match
		...
		if (!match) {
			Log.error(String.format("File not found: '%s'", tokens[1]));
			return null;
		}
	}
```
This isn't a bug unless the file actually exists.  Could you check?

**Comment by chong601** [comment]
I think finding the culprit will be a bit tough since it happens randomly in 30k+ of maps XD
Will look into it when I reach home.
(the thimg is, where the word virtual comes from? Didn't saw them anywhere near it)

**Comment by itdelatrisu** [comment]
...yeah, that's a really bad error message, sorry.  Try this instead:
```
Log.error(String.format("Audio file '%s' not found in directory '%s'.", tokens[1], dir.getName()));
```

**Comment by LemonLake** [comment]
Just use a file search, text editors have them

**Comment by chong601** [comment]
Added the updated error message and still have no idea where the file virtual is lol
Apparently the maps affected are mania maps... investigating now
The log message:
```
Fri Apr 10 22:03:46 SGT 2015 ERROR:Audio file 'virtual' not found in directory '152065 Ras - STAGER'.
Fri Apr 10 22:03:46 SGT 2015 ERROR:Audio file 'virtual' not found in directory '152065 Ras - STAGER'.
Fri Apr 10 22:03:46 SGT 2015 ERROR:Audio file 'virtual' not found in directory '152065 Ras - STAGER'.
Fri Apr 10 22:03:53 SGT 2015 ERROR:Audio file 'virtual' not found in directory '92190 Yuuna Sasara feat Tai no Kobone - Imperishable Night 2006'.
Fri Apr 10 22:03:53 SGT 2015 ERROR:Audio file 'virtual' not found in directory '92190 Yuuna Sasara feat Tai no Kobone - Imperishable Night 2006'.
Fri Apr 10 22:03:53 SGT 2015 ERROR:Audio file 'virtual' not found in directory '92190 Yuuna Sasara feat Tai no Kobone - Imperishable Night 2006'.
Fri Apr 10 22:03:53 SGT 2015 ERROR:Audio file 'virtual' not found in directory '92190 Yuuna Sasara feat Tai no Kobone - Imperishable Night 2006'.
Fri Apr 10 22:03:53 SGT 2015 ERROR:Audio file 'virtual' not found in directory '92190 Yuuna Sasara feat Tai no Kobone - Imperishable Night 2006'.
Fri Apr 10 22:03:53 SGT 2015 ERROR:Audio file 'virtual' not found in directory '92190 Yuuna Sasara feat Tai no Kobone - Imperishable Night 2006'.

```

**Comment by chong601** [comment]
UPDATE: Found the culprit...
Apparently on mania maps, there's a type of map called keysounded maps (maps that doesn't have music, the effects themselves are the music)
The 'virtual' file name is in their respective osu! files to "cheat" osu! to not load any music since as long the mania keys are pressed accordingly, it will form a music...
![The contents of the affected .osu file](http://puu.sh/h8BCN.png)
I think it is safe to close this issue xD
