### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by Jackall4BDN** [itdelatrisu/opsu#77]
Whenever i try to start opsu! i get an uncaught sql-exception of this or a similar kind:
Sun Apr 12 21:22:27 CEST 2015 ERROR:** Uncaught Exception! **
Sun Apr 12 21:22:27 CEST 2015 ERROR:org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
	at org.sqlite.core.NativeDB._open(Native Method)
	at org.sqlite.core.DB.open(DB.java:161)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:145)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.OsuDB.init(OsuDB.java:74)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:46)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:138)

I reinstalled java allready and got no other sql-application running whatsoever. I didn't look at the sourcecode, but from the looks the library for sqlite is broken or plainly not compatible on my end...

**Comment by itdelatrisu** [comment]
What version of opsu! are you running?  If it's not the latest, try updating.  Otherwise, please include information about your OS, architecture, etc.

**Comment by Jackall4BDN** [comment]
I'm on Windows 8.1 x64, JRE, JDK are installed in both 32 and 64 bit but i am running my .jars on the 32bit JRE, i made sure i got acess-rights to my opsu!- and osu!-directory, G:/opsu!/ and G:/osu!/, and allready tried with configurations for skins and songs in both paths (if that matters anything), with and without the "\.\" (for whatever reason you included that, pardon me if i missed something essential on windows or java here, but that seems just wrong to me)

Not much more to say about my system, it run's everything else fine.

**Comment by itdelatrisu** [comment]
Try changing the path to `G:/opsu/` instead (without `!`) -- JARs can't be loaded from a path containing `!`.  This has been an open bug in Java for a decade, so it doesn't look like anyone's going to fix it...

And thanks! TT was really fun to rewrite, though I probably spent half my time "testing" it. :P

**Comment by Jackall4BDN** [comment]
omg, that really did the trick, thx xD
that it was that simple... i could have known, since i code in java aswell, but i never EVER had any unworking symbols let alone a "!" in any directory xD

**Comment by itdelatrisu** [comment]
I don't know if I'll ever get to it, to be honest -- I've gotten much busier and it'd probably take me some time to throw together a reliable server for it.  If you want to write one, I'd be happy to link to it, though!  (Closing this report, but feel free to keep commenting here or wherever.)

**Comment by Jackall4BDN** [comment]
in about a month my final exams are over and before applying at an university i wanted to take a year of break, so i will have a heckload of freetime, maybe i will look into it, then^^

**Comment by chong601** [comment]
a workaround, you can set the BeatmapDirectory to your osu! folder like this
![Image](http://puu.sh/hb4Jh.png)

**Comment by Jackall4BDN** [comment]
thx, but that does not apply to the problem i had, it wouldn't even work for that matter. also it has been resolved allready
