### ISSUE TITLE
Intermittant visual jitter during gameplay

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#80]
During a play, the graphics jitters for a short while (about 5-10 seconds) and then it smooths out.
The FPS value did not drop during the jitter.
It seems to be happening before a slider or a very dense streams (>150 bpm)

**Comment by itdelatrisu** [comment]
Does this still happen?

**Comment by chong601** [comment]
As of the previous commit (7d08a7d39128a3d0d14485a888adadb3714630d5), it seems to be quite stable (no noticeable jitters)

Will try checking out the latest commit tomorrow (if i have time)
