### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by shiinom** [itdelatrisu/opsu#81]
**Version:** 0.8.0
**Build date:** 2015-03-20 04:45
**OS:** Windows 7 (amd64)
**JRE:** 1.8.0_45
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.ArrayIndexOutOfBoundsException: 10
	at org.newdawn.slick.Input.poll(Input.java:1314)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:93)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:169)
```

**Comment by chong601** [comment]
did you happen to use touchscreen? (that's some weird error you have there)

**Comment by shiinom** [comment]
I have a wacom intous 480, but not a touchscreen

**Comment by chong601** [comment]
can't really pinpoint the issue but it seems to be due to Slick unable to handle something from input (either touch or keyboard)

**Comment by itdelatrisu** [comment]
I added a try-catch inside the loop causing the error -- can you run this and see if it still crashes?
http://www.mediafire.com/download/ldbj24d1yldd24o/opsu-0.8.0-runnable.jar

**Comment by shiinom** [comment]
It works now, thank you
