### ISSUE TITLE
Can't move the .jar ?

### ISSUE THREAD

**Issue by ItemME** [itdelatrisu/opsu#82]
Hi there !
So i got a problem with your jar (just testing for now, because i don't really understand how to compile & edit the code for now, since i've never worked before in this type of java)
So i launched your .jar in download folder first to test it, then it creates everything needed to run it properly, and actually it run properly.
But when i try to launch the .jar from anywhere else (a folder on my desktop for example) i got this issue : 
"** Uncaught Exception! **
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
	at org.sqlite.core.NativeDB._open(Native Method)
	at org.sqlite.core.DB.open(DB.java:161)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:145)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.OsuDB.init(OsuDB.java:74)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:46)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:138)
"

I've also try to download the release, again, but same problem appear.
Also, if someway you can tell me how can i edit & compile to help you, it would be awesome.
I'm working mainly in C#, or web langages, but i think i'll handle java ^^ Just need to know how to run that x)

**Comment by ItemME** [comment]
Well, i guess i'm sorry about the inconvenient i finally find why.
(.cfg mistake from me)
But if you still could help me about editing code & compiling, it would be great ^^ (or redirect to a topic that i didn't saw)

Thanks in advance !

**Comment by itdelatrisu** [comment]
You have to install a JDK (7 or 8), then install [Maven](https://maven.apache.org/) to use the commands in the [readme](https://github.com/itdelatrisu/opsu#building).  If you use [Eclipse](http://eclipse.org/downloads/), the Maven plugin is pretty great, too -- you can import the project as a Maven project by selecting its "pom.xml", and the plugin will set everything up automatically.

As for the code, the main class is `Opsu`, which initializes all the states (in the `opsu.states` package) and then enters the first one (the splash screen).  Everything's pretty well documented, I think, so it shouldn't be hard to skim through the states to see what the basic structure is.

I'm going to close this report, but feel free to keep commenting here.

**Comment by Bigpet** [comment]
>If you use Eclipse, the Maven plugin is pretty great, too

And if you don't use Eclipse, both Netbeans and IntelliJ have excellent Maven plugins too :smiley:

**Comment by LemonLake** [comment]
I think all IDEs have great Maven plugins ;)

**Comment by itdelatrisu** [comment]
Good to know. xD

**Comment by ItemME** [comment]
Thanks everybody !
Yes, i wanted to use Eclipse, and good to see that Maven work with it ^^
But i think i have some troubles with java, eclipse exit with code 13
The problem come from my JVM (Actually JRE) if the documentation is correct.
Anyone had the same issue ?

**Comment by ItemME** [comment]
Well .. I guess something went wrong when i installed JDK, now eclispe start well ^^ 
Thanks !

**Comment by LemonLake** [comment]
Sorry to necro, but what do you mean by 'this type of java'? Are you mixing
up Java and JavaScript?
