### ISSUE TITLE
Stuttering while switching from 2x to .5x Playback rate

### ISSUE THREAD

**Issue by marshallracer** [itdelatrisu/opsu#86]
I just downloaded the 0.9.0 build to see how the playback rate changes are looking and I've come across some stuttering when changing from 2x to .5 rate.
I tried it out with every frame limiter, with Auto mod and own replays, suttering in every case.
Cannot surely tell if it's just a problem on my end but I just wanted to let you know. It's nothing too bad I assume, it's just something I noticed.

Also, a short Video to demonstrate the issue : https://youtu.be/nQbPZMsfcv4

**Comment by itdelatrisu** [comment]
Thanks for the report.  I noticed this earlier too, but haven't looked into it yet.  I'd guess that it's either an issue with speed/pitch changing in LWJGL or a precision issue with Slick's Music player.  In any case, it's likely a tough problem; if you (or anyone else) care enough, feel free to look deeper.

This probably won't be an issue if we follow through with #78, though I can't say if/when that will happen.
