### ISSUE TITLE
Add fullscreen mode

### ISSUE THREAD

**Issue by stdex** [itdelatrisu/opsu#88]
Add fullscreen mode or abulitty to change windows size.

**Comment by itdelatrisu** [comment]
You can change the window size in the settings menu.  OpenGL fullscreen mode is extremely buggy from what I tried, but if you can get it to work, please let me know how.

**Comment by LemonLake** [comment]
Borderless windows can be implemented in LWJGL by setting the property `org.lwjgl.opengl.Window.undecorated` to true (`-Dorg.lwjgl.opengl.Window.undecorated`)

    System.setProperty("org.lwjgl.opengl.Window.undecorated", "true");

However, as it is a property it must be done before starting the game - requiring a restart. Not very convenient, but most other changes currently require a restart anyway.

Another solution is to create a JFrame and bind the surface to a canvas, however I am not sure about the impacts this will have on input and performance. Will test later.

**Comment by itdelatrisu** [comment]
@LemonLake: Oh, I interpreted "fullscreen mode" as Slick2D's `AppGameContainer.setDisplayMode(w, h, fullscreen)` -- which, if you try it, produces some very strange results.  I'm already setting the LWJGL "undecorated" property if the game resolution matches the screen resolution.  There's a `CanvasGameContainer` class in Slick2D, but iirc it's generally not used.

**Comment by LemonLake** [comment]
Yeah, your interpretation was correct actually, I was just suggesting
windowed-fullscreen as that's at least my personal preference :p

**Comment by itdelatrisu** [comment]
Maybe I'll just add "windowed fullscreen" as a resolution option...

**Comment by LemonLake** [comment]
No need, it was a misobservation on my part. osu! ítself does the same - if the resolution matches native, it's borderless.
