### ISSUE TITLE
How to calculate HIT_300 offset in milliseconds?

### ISSUE THREAD

**Issue by AndreySeVeN** [itdelatrisu/opsu#96]

**Comment by AndreySeVeN** [comment]
g.fillRect((hitErrorX - 3 - hitResultOffset[HIT_300]) * uiScale, barY,
					(hitResultOffset[HIT_300] * 2) * uiScale, barHeight);

hitResultOffset[HIT_300] How to calculate?

**Comment by itdelatrisu** [comment]
https://github.com/itdelatrisu/opsu/blob/0112a03bd38f18543f27cc9d39e285d598e60e9e/src/itdelatrisu/opsu/states/Game.java#L1407
```
		hitResultOffset[GameData.HIT_300]  = (int) (78 - (overallDifficulty * 6));
		hitResultOffset[GameData.HIT_100]  = (int) (138 - (overallDifficulty * 8));
		hitResultOffset[GameData.HIT_50]   = (int) (198 - (overallDifficulty * 10));
		hitResultOffset[GameData.HIT_MISS] = (int) (500 - (overallDifficulty * 10));
```

**Comment by AndreySeVeN** [comment]
This is... note time + hitResultOffset[GameData.HIT_300] = Hit300 max(right)? And... note time - hitResultOffset[gameData.HIT_300] = Hit300 min(left)?

**Comment by itdelatrisu** [comment]
I don't understand the question.  Could you explain?

**Comment by AndreySeVeN** [comment]
Yes... can add in Skype?

**Comment by itdelatrisu** [comment]
I'd prefer if you asked here, if possible.

**Comment by AndreySeVeN** [comment]
http://image.openlan.ru/images/79381508774879688326.png

**Comment by itdelatrisu** [comment]
The ticks?  https://github.com/itdelatrisu/opsu/blob/0112a03bd38f18543f27cc9d39e285d598e60e9e/src/itdelatrisu/opsu/GameData.java#L679
```

			// draw ticks
			float tickWidth = 2 * uiScale;
			for (HitErrorInfo info : hitErrorList) {
				int time = info.time;
				float alpha = 1 - ((float) (trackPosition - time) / HIT_ERROR_FADE_TIME);
				white.a = alpha * hitErrorAlpha;
				g.setColor(white);
				g.fillRect((hitErrorX + info.timeDiff - 1) * uiScale, tickY, tickWidth, tickHeight);
			}
```

**Comment by AndreySeVeN** [comment]
How to get time in milliseconds?

**Comment by AndreySeVeN** [comment]
Time of circle - (3 - hitResultOffset[HIT_300]) * uiScale) = Minimal value for get 300?
